# [target.aarch64-unknown-linux-gnu]
# pre-build = [
#   "dpkg --add-architecture $CROSS_DEB_ARCH",
#   "apt-get update",
#   "apt-get install --assume-yes nasm:$CROSS_DEB_ARCH",
# ]
[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:edge"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update",
  "apt-get install --assume-yes nasm",
]
# [target.armv7-unknown-linux-musleabihf]
# pre-build = [
#   "dpkg --add-architecture $CROSS_DEB_ARCH",
#   "apt-get update",
#   "apt-get install --assume-yes nasm:$CROSS_DEB_ARCH",
# ]

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:edge"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update",
  "apt-get install --assume-yes nasm:$CROSS_DEB_ARCH",
]

[target.armv7-unknown-linux-musleabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:edge"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update",
  "apt-get install --assume-yes nasm:$CROSS_DEB_ARCH",
]

[target.arm-unknown-linux-gnueabihf]
pre-build = [
  # Update package list
  "apt-get update",
  # Upgrade installed packages
  "apt-get upgrade --assume-yes",
  "apt-get install --assume-yes nasm curl",
  # Add NodeSource repository for Node.js 20
  "curl -fsSL https://deb.nodesource.com/setup_20.x | bash",
  "apt-get install --assume-yes nodejs",
  # Install pnpm via npm
  "npm install -g pnpm"
]

