export const WebsiteTemplateImage: React.FC = () => {
  return (
    <svg width='1803' height='1200' viewBox='0 0 1803 1200' fill='none'>
      <g clipPath='url(#clip0_930_4)'>
        <rect width='1803' height='1200' fill='var(--template-color-bg' />
        <rect width='1920' height='130' fill='var(--template-color-bg1)' />
        <rect
          x='116'
          y='37'
          width='258'
          height='55'
          rx='15'
          fill='var(--template-color-bg'
        />
        <rect
          x='1548'
          y='49'
          width='139'
          height='32'
          rx='15'
          fill='var(--template-color-bg'
        />
        <rect
          x='1363'
          y='49'
          width='139'
          height='32'
          rx='15'
          fill='var(--template-color-bg'
        />
        <rect
          x='1178'
          y='49'
          width='139'
          height='32'
          rx='15'
          fill='var(--template-color-bg'
        />
        <rect
          x='117'
          y='201'
          width='944'
          height='87'
          rx='15'
          fill='var(--template-color-bg2)'
        />
        <rect
          x='117'
          y='357'
          width='718'
          height='29'
          rx='15'
          fill='var(--template-color-bg1)'
        />
        <rect
          x='117'
          y='417'
          width='846'
          height='29'
          rx='15'
          fill='var(--template-color-bg1)'
        />
        <rect
          x='117'
          y='477'
          width='798'
          height='29'
          rx='15'
          fill='var(--template-color-bg1)'
        />
        <rect
          x='117'
          y='537'
          width='694'
          height='29'
          rx='15'
          fill='var(--template-color-bg1)'
        />
        <rect
          x='117'
          y='597'
          width='857'
          height='29'
          rx='15'
          fill='var(--template-color-bg1)'
        />
        <rect
          x='117'
          y='657'
          width='760'
          height='29'
          rx='15'
          fill='var(--template-color-bg1)'
        />
        <rect
          x='116'
          y='755'
          width='430'
          height='369'
          rx='15'
          fill='var(--template-color-bg1)'
        />
        <rect
          x='687'
          y='755'
          width='430'
          height='369'
          rx='15'
          fill='var(--template-color-bg1)'
        />
        <rect
          x='1258'
          y='755'
          width='430'
          height='369'
          rx='15'
          fill='var(--template-color-bg1)'
        />
      </g>
    </svg>
  );
};
