// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_drive_materialized`, `fetch_resource_state`, `handle_ws_message`, `ws_client_slot`, `ws_task_slot`

/// `http://host:9883` → `ws://host:9883/ws`
Future<String> serverOriginToWsUrl({required String origin}) =>
    RustLib.instance.api
        .crateApiSimpleWsSyncServerOriginToWsUrl(origin: origin);

Future<void> closeWsSync() =>
    RustLib.instance.api.crateApiSimpleWsSyncCloseWsSync();

Future<void> openWsSync({required String serverOrigin}) => RustLib.instance.api
    .crateApiSimpleWsSyncOpenWsSync(serverOrigin: serverOrigin);

/// Best-effort: push a locally signed commit over WS when a session is open.
/// Returns `true` if the commit was accepted by the hub.
Future<bool> tryPushCommit({required Db store, required Commit commit}) =>
    RustLib.instance.api
        .crateApiSimpleWsSyncTryPushCommit(store: store, commit: commit);

/// Subscribe to live updates for a single canvas over WebSocket.
Future<void> subscribeCanvas({required String subject}) =>
    RustLib.instance.api.crateApiSimpleWsSyncSubscribeCanvas(subject: subject);

/// Post a commit JSON-AD over the open WS session (falls back to error if closed).
Future<String> postCommitOverWs({required String commitJson}) =>
    RustLib.instance.api
        .crateApiSimpleWsSyncPostCommitOverWs(commitJson: commitJson);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Commit>>
abstract class Commit implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Db>>
abstract class Db implements RustOpaqueInterface {}
