// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/meals.dart';
import 'api/simple.dart';
import 'api/simple/types.dart';
import 'api/simple/ws_sync.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1627092819;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_calorie_tracker',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  void crateApiSimpleAddKnownPeer(
      {required String nodeId, required String name});

  AgentInfo crateApiSimpleAgentFromSecret({required String secret});

  Future<void> crateApiSimpleClearAgent();

  Future<void> crateApiSimpleCloseWsSync();

  Future<void> crateApiSimpleWsSyncCloseWsSync();

  AgentInfo crateApiSimpleCreateAgent({required String name});

  Future<String> crateApiSimpleCreateDrive({required String name});

  Future<String> crateApiMealsCreateMeal(
      {required PlatformInt64 consumedAtMs,
      required String name,
      required String notes,
      required String imagePath,
      PlatformInt64? calories});

  Future<String> crateApiSimpleCreateResource(
      {required String parentSubject,
      required String name,
      required String class_});

  Future<void> crateApiSimpleDeleteResource({required String subject});

  Future<String> crateApiMealsEnsureMealsContainer();

  Future<AgentInfo?> crateApiSimpleGetActiveAgent();

  String? crateApiSimpleGetActiveDrive();

  String crateApiSimpleGetDeviceName();

  String crateApiSimpleGetKnownPeers();

  String crateApiSimpleGetKnownPeersJson();

  Future<MealItem?> crateApiMealsGetMeal({required String subject});

  String? crateApiSimpleGetPeerId();

  Future<String> crateApiSimpleGetProperty(
      {required String subject, required String property});

  Future<String> crateApiSimpleGetPropertyAtVersion(
      {required String subject,
      required List<int> versionId,
      required String property});

  Future<List<VersionMetadata>> crateApiSimpleGetResourceHistory(
      {required String subject});

  Future<void> crateApiSimpleInitApp();

  Future<List<String>> crateApiSimpleListDrives();

  Future<String> crateApiSimpleListDrivesWithNames();

  Future<List<MealItem>> crateApiMealsListMeals(
      {required PlatformInt64 fromMs, required PlatformInt64 toMs});

  Future<List<MealItem>> crateApiMealsListPendingMeals();

  int crateApiSimpleLivePeerCount();

  List<String> crateApiSimpleLivePeerIds();

  Future<String> crateApiSimpleLoadAgent({required String secret});

  Future<void> crateApiSimpleOpenDb({required String path});

  Future<void> crateApiSimpleOpenWsSync({required String serverUrl});

  Future<void> crateApiSimpleWsSyncOpenWsSync({required String serverOrigin});

  Future<void> crateApiSimplePeerAnnounce({required String driveSubject});

  Future<int> crateApiSimplePeerDiscoverSync({required String driveSubject});

  Future<String> crateApiSimplePeerSync({required String nodeId});

  Future<String?> crateApiSimplePollDbEvent({required int timeoutMs});

  Future<String> crateApiSimplePollSyncEvents();

  Future<String> crateApiSimpleWsSyncPostCommitOverWs(
      {required String commitJson});

  void crateApiSimpleRemoveKnownPeer({required String nodeId});

  Future<void> crateApiSimpleRenameResource(
      {required String subject, required String name});

  Future<String> crateApiSimpleResumeAppSession(
      {required String serverUrl, required String secret, String? driveHint});

  Future<String> crateApiSimpleWsSyncServerOriginToWsUrl(
      {required String origin});

  Future<void> crateApiSimpleSetActiveDrive({required String subject});

  void crateApiSimpleSetDeviceName({required String name});

  Future<void> crateApiMealsSetMealStatus(
      {required String subject, required String status});

  Future<void> crateApiSimpleSetProperty(
      {required String subject,
      required String property,
      required String value});

  Future<SetupResult> crateApiSimpleSetup({required String name});

  Future<String> crateApiSimpleStartPeer();

  Future<void> crateApiSimpleWsSyncSubscribeResource({required String subject});

  Future<String> crateApiSimpleSyncConnectivityNow();

  Future<int> crateApiSimpleSyncDriveToServer({required String serverUrl});

  Future<void> crateApiMealsUpdateMeal(
      {required String subject,
      String? name,
      String? notes,
      PlatformInt64? calories});

  Future<void> crateApiMealsUpdateMealEstimate(
      {required String subject, required MealEstimate estimate});

  Future<int> crateApiSimpleWaitForPeerCountChange({required int current});

  Future<String> crateApiSimpleWaitForSyncEvent();

  Future<void> crateApiSimpleWarmResourceHistory({required String subject});

  Future<String> crateApiSimpleWatchChildren({required String parent});

  Future<String> crateApiSimpleWatchResource({required String subject});

  Future<void> crateApiSimpleWsSubscribeResource({required String subject});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiSimpleAddKnownPeer(
      {required String nodeId, required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeId, serializer);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleAddKnownPeerConstMeta,
      argValues: [nodeId, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleAddKnownPeerConstMeta => const TaskConstMeta(
        debugName: "add_known_peer",
        argNames: ["nodeId", "name"],
      );

  @override
  AgentInfo crateApiSimpleAgentFromSecret({required String secret}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(secret, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_agent_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleAgentFromSecretConstMeta,
      argValues: [secret],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleAgentFromSecretConstMeta =>
      const TaskConstMeta(
        debugName: "agent_from_secret",
        argNames: ["secret"],
      );

  @override
  Future<void> crateApiSimpleClearAgent() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleClearAgentConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleClearAgentConstMeta => const TaskConstMeta(
        debugName: "clear_agent",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleCloseWsSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCloseWsSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCloseWsSyncConstMeta => const TaskConstMeta(
        debugName: "close_ws_sync",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleWsSyncCloseWsSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleWsSyncCloseWsSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWsSyncCloseWsSyncConstMeta =>
      const TaskConstMeta(
        debugName: "close_ws_sync",
        argNames: [],
      );

  @override
  AgentInfo crateApiSimpleCreateAgent({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_agent_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCreateAgentConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCreateAgentConstMeta => const TaskConstMeta(
        debugName: "create_agent",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiSimpleCreateDrive({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCreateDriveConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCreateDriveConstMeta => const TaskConstMeta(
        debugName: "create_drive",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiMealsCreateMeal(
      {required PlatformInt64 consumedAtMs,
      required String name,
      required String notes,
      required String imagePath,
      PlatformInt64? calories}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(consumedAtMs, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(notes, serializer);
        sse_encode_String(imagePath, serializer);
        sse_encode_opt_box_autoadd_i_64(calories, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMealsCreateMealConstMeta,
      argValues: [consumedAtMs, name, notes, imagePath, calories],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMealsCreateMealConstMeta => const TaskConstMeta(
        debugName: "create_meal",
        argNames: ["consumedAtMs", "name", "notes", "imagePath", "calories"],
      );

  @override
  Future<String> crateApiSimpleCreateResource(
      {required String parentSubject,
      required String name,
      required String class_}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(parentSubject, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(class_, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCreateResourceConstMeta,
      argValues: [parentSubject, name, class_],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCreateResourceConstMeta =>
      const TaskConstMeta(
        debugName: "create_resource",
        argNames: ["parentSubject", "name", "class_"],
      );

  @override
  Future<void> crateApiSimpleDeleteResource({required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleDeleteResourceConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleDeleteResourceConstMeta =>
      const TaskConstMeta(
        debugName: "delete_resource",
        argNames: ["subject"],
      );

  @override
  Future<String> crateApiMealsEnsureMealsContainer() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMealsEnsureMealsContainerConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMealsEnsureMealsContainerConstMeta =>
      const TaskConstMeta(
        debugName: "ensure_meals_container",
        argNames: [],
      );

  @override
  Future<AgentInfo?> crateApiSimpleGetActiveAgent() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_agent_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetActiveAgentConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetActiveAgentConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_agent",
        argNames: [],
      );

  @override
  String? crateApiSimpleGetActiveDrive() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGetActiveDriveConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetActiveDriveConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_drive",
        argNames: [],
      );

  @override
  String crateApiSimpleGetDeviceName() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetDeviceNameConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetDeviceNameConstMeta =>
      const TaskConstMeta(
        debugName: "get_device_name",
        argNames: [],
      );

  @override
  String crateApiSimpleGetKnownPeers() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGetKnownPeersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetKnownPeersConstMeta =>
      const TaskConstMeta(
        debugName: "get_known_peers",
        argNames: [],
      );

  @override
  String crateApiSimpleGetKnownPeersJson() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGetKnownPeersJsonConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetKnownPeersJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_known_peers_json",
        argNames: [],
      );

  @override
  Future<MealItem?> crateApiMealsGetMeal({required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_meal_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMealsGetMealConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMealsGetMealConstMeta => const TaskConstMeta(
        debugName: "get_meal",
        argNames: ["subject"],
      );

  @override
  String? crateApiSimpleGetPeerId() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGetPeerIdConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetPeerIdConstMeta => const TaskConstMeta(
        debugName: "get_peer_id",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleGetProperty(
      {required String subject, required String property}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_String(property, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetPropertyConstMeta,
      argValues: [subject, property],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetPropertyConstMeta => const TaskConstMeta(
        debugName: "get_property",
        argNames: ["subject", "property"],
      );

  @override
  Future<String> crateApiSimpleGetPropertyAtVersion(
      {required String subject,
      required List<int> versionId,
      required String property}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_list_prim_u_8_loose(versionId, serializer);
        sse_encode_String(property, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetPropertyAtVersionConstMeta,
      argValues: [subject, versionId, property],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetPropertyAtVersionConstMeta =>
      const TaskConstMeta(
        debugName: "get_property_at_version",
        argNames: ["subject", "versionId", "property"],
      );

  @override
  Future<List<VersionMetadata>> crateApiSimpleGetResourceHistory(
      {required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_version_metadata,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetResourceHistoryConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetResourceHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "get_resource_history",
        argNames: ["subject"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiSimpleListDrives() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleListDrivesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleListDrivesConstMeta => const TaskConstMeta(
        debugName: "list_drives",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleListDrivesWithNames() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleListDrivesWithNamesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleListDrivesWithNamesConstMeta =>
      const TaskConstMeta(
        debugName: "list_drives_with_names",
        argNames: [],
      );

  @override
  Future<List<MealItem>> crateApiMealsListMeals(
      {required PlatformInt64 fromMs, required PlatformInt64 toMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(fromMs, serializer);
        sse_encode_i_64(toMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_meal_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMealsListMealsConstMeta,
      argValues: [fromMs, toMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMealsListMealsConstMeta => const TaskConstMeta(
        debugName: "list_meals",
        argNames: ["fromMs", "toMs"],
      );

  @override
  Future<List<MealItem>> crateApiMealsListPendingMeals() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_meal_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMealsListPendingMealsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMealsListPendingMealsConstMeta =>
      const TaskConstMeta(
        debugName: "list_pending_meals",
        argNames: [],
      );

  @override
  int crateApiSimpleLivePeerCount() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleLivePeerCountConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleLivePeerCountConstMeta =>
      const TaskConstMeta(
        debugName: "live_peer_count",
        argNames: [],
      );

  @override
  List<String> crateApiSimpleLivePeerIds() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleLivePeerIdsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleLivePeerIdsConstMeta => const TaskConstMeta(
        debugName: "live_peer_ids",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleLoadAgent({required String secret}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(secret, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleLoadAgentConstMeta,
      argValues: [secret],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleLoadAgentConstMeta => const TaskConstMeta(
        debugName: "load_agent",
        argNames: ["secret"],
      );

  @override
  Future<void> crateApiSimpleOpenDb({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleOpenDbConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleOpenDbConstMeta => const TaskConstMeta(
        debugName: "open_db",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiSimpleOpenWsSync({required String serverUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(serverUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleOpenWsSyncConstMeta,
      argValues: [serverUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleOpenWsSyncConstMeta => const TaskConstMeta(
        debugName: "open_ws_sync",
        argNames: ["serverUrl"],
      );

  @override
  Future<void> crateApiSimpleWsSyncOpenWsSync({required String serverOrigin}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(serverOrigin, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleWsSyncOpenWsSyncConstMeta,
      argValues: [serverOrigin],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWsSyncOpenWsSyncConstMeta =>
      const TaskConstMeta(
        debugName: "open_ws_sync",
        argNames: ["serverOrigin"],
      );

  @override
  Future<void> crateApiSimplePeerAnnounce({required String driveSubject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(driveSubject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimplePeerAnnounceConstMeta,
      argValues: [driveSubject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimplePeerAnnounceConstMeta => const TaskConstMeta(
        debugName: "peer_announce",
        argNames: ["driveSubject"],
      );

  @override
  Future<int> crateApiSimplePeerDiscoverSync({required String driveSubject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(driveSubject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimplePeerDiscoverSyncConstMeta,
      argValues: [driveSubject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimplePeerDiscoverSyncConstMeta =>
      const TaskConstMeta(
        debugName: "peer_discover_sync",
        argNames: ["driveSubject"],
      );

  @override
  Future<String> crateApiSimplePeerSync({required String nodeId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimplePeerSyncConstMeta,
      argValues: [nodeId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimplePeerSyncConstMeta => const TaskConstMeta(
        debugName: "peer_sync",
        argNames: ["nodeId"],
      );

  @override
  Future<String?> crateApiSimplePollDbEvent({required int timeoutMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(timeoutMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimplePollDbEventConstMeta,
      argValues: [timeoutMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimplePollDbEventConstMeta => const TaskConstMeta(
        debugName: "poll_db_event",
        argNames: ["timeoutMs"],
      );

  @override
  Future<String> crateApiSimplePollSyncEvents() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimplePollSyncEventsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimplePollSyncEventsConstMeta =>
      const TaskConstMeta(
        debugName: "poll_sync_events",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleWsSyncPostCommitOverWs(
      {required String commitJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(commitJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 38, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleWsSyncPostCommitOverWsConstMeta,
      argValues: [commitJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWsSyncPostCommitOverWsConstMeta =>
      const TaskConstMeta(
        debugName: "post_commit_over_ws",
        argNames: ["commitJson"],
      );

  @override
  void crateApiSimpleRemoveKnownPeer({required String nodeId}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(nodeId, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleRemoveKnownPeerConstMeta,
      argValues: [nodeId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleRemoveKnownPeerConstMeta =>
      const TaskConstMeta(
        debugName: "remove_known_peer",
        argNames: ["nodeId"],
      );

  @override
  Future<void> crateApiSimpleRenameResource(
      {required String subject, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 40, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleRenameResourceConstMeta,
      argValues: [subject, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleRenameResourceConstMeta =>
      const TaskConstMeta(
        debugName: "rename_resource",
        argNames: ["subject", "name"],
      );

  @override
  Future<String> crateApiSimpleResumeAppSession(
      {required String serverUrl, required String secret, String? driveHint}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(serverUrl, serializer);
        sse_encode_String(secret, serializer);
        sse_encode_opt_String(driveHint, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 41, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleResumeAppSessionConstMeta,
      argValues: [serverUrl, secret, driveHint],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleResumeAppSessionConstMeta =>
      const TaskConstMeta(
        debugName: "resume_app_session",
        argNames: ["serverUrl", "secret", "driveHint"],
      );

  @override
  Future<String> crateApiSimpleWsSyncServerOriginToWsUrl(
      {required String origin}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(origin, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 42, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleWsSyncServerOriginToWsUrlConstMeta,
      argValues: [origin],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWsSyncServerOriginToWsUrlConstMeta =>
      const TaskConstMeta(
        debugName: "server_origin_to_ws_url",
        argNames: ["origin"],
      );

  @override
  Future<void> crateApiSimpleSetActiveDrive({required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 43, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSetActiveDriveConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetActiveDriveConstMeta =>
      const TaskConstMeta(
        debugName: "set_active_drive",
        argNames: ["subject"],
      );

  @override
  void crateApiSimpleSetDeviceName({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSetDeviceNameConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetDeviceNameConstMeta =>
      const TaskConstMeta(
        debugName: "set_device_name",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiMealsSetMealStatus(
      {required String subject, required String status}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_String(status, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 45, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMealsSetMealStatusConstMeta,
      argValues: [subject, status],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMealsSetMealStatusConstMeta => const TaskConstMeta(
        debugName: "set_meal_status",
        argNames: ["subject", "status"],
      );

  @override
  Future<void> crateApiSimpleSetProperty(
      {required String subject,
      required String property,
      required String value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_String(property, serializer);
        sse_encode_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 46, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSetPropertyConstMeta,
      argValues: [subject, property, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetPropertyConstMeta => const TaskConstMeta(
        debugName: "set_property",
        argNames: ["subject", "property", "value"],
      );

  @override
  Future<SetupResult> crateApiSimpleSetup({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 47, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_setup_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSetupConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetupConstMeta => const TaskConstMeta(
        debugName: "setup",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiSimpleStartPeer() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 48, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleStartPeerConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleStartPeerConstMeta => const TaskConstMeta(
        debugName: "start_peer",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleWsSyncSubscribeResource(
      {required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 49, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleWsSyncSubscribeResourceConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWsSyncSubscribeResourceConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_resource",
        argNames: ["subject"],
      );

  @override
  Future<String> crateApiSimpleSyncConnectivityNow() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 50, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSyncConnectivityNowConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSyncConnectivityNowConstMeta =>
      const TaskConstMeta(
        debugName: "sync_connectivity_now",
        argNames: [],
      );

  @override
  Future<int> crateApiSimpleSyncDriveToServer({required String serverUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(serverUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 51, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_32,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSyncDriveToServerConstMeta,
      argValues: [serverUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSyncDriveToServerConstMeta =>
      const TaskConstMeta(
        debugName: "sync_drive_to_server",
        argNames: ["serverUrl"],
      );

  @override
  Future<void> crateApiMealsUpdateMeal(
      {required String subject,
      String? name,
      String? notes,
      PlatformInt64? calories}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_opt_String(name, serializer);
        sse_encode_opt_String(notes, serializer);
        sse_encode_opt_box_autoadd_i_64(calories, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 52, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMealsUpdateMealConstMeta,
      argValues: [subject, name, notes, calories],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMealsUpdateMealConstMeta => const TaskConstMeta(
        debugName: "update_meal",
        argNames: ["subject", "name", "notes", "calories"],
      );

  @override
  Future<void> crateApiMealsUpdateMealEstimate(
      {required String subject, required MealEstimate estimate}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_box_autoadd_meal_estimate(estimate, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 53, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiMealsUpdateMealEstimateConstMeta,
      argValues: [subject, estimate],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMealsUpdateMealEstimateConstMeta =>
      const TaskConstMeta(
        debugName: "update_meal_estimate",
        argNames: ["subject", "estimate"],
      );

  @override
  Future<int> crateApiSimpleWaitForPeerCountChange({required int current}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(current, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 54, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleWaitForPeerCountChangeConstMeta,
      argValues: [current],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWaitForPeerCountChangeConstMeta =>
      const TaskConstMeta(
        debugName: "wait_for_peer_count_change",
        argNames: ["current"],
      );

  @override
  Future<String> crateApiSimpleWaitForSyncEvent() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 55, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleWaitForSyncEventConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWaitForSyncEventConstMeta =>
      const TaskConstMeta(
        debugName: "wait_for_sync_event",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleWarmResourceHistory({required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 56, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleWarmResourceHistoryConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWarmResourceHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "warm_resource_history",
        argNames: ["subject"],
      );

  @override
  Future<String> crateApiSimpleWatchChildren({required String parent}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(parent, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 57, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleWatchChildrenConstMeta,
      argValues: [parent],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWatchChildrenConstMeta =>
      const TaskConstMeta(
        debugName: "watch_children",
        argNames: ["parent"],
      );

  @override
  Future<String> crateApiSimpleWatchResource({required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 58, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleWatchResourceConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWatchResourceConstMeta =>
      const TaskConstMeta(
        debugName: "watch_resource",
        argNames: ["subject"],
      );

  @override
  Future<void> crateApiSimpleWsSubscribeResource({required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 59, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleWsSubscribeResourceConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleWsSubscribeResourceConstMeta =>
      const TaskConstMeta(
        debugName: "ws_subscribe_resource",
        argNames: ["subject"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentInfo dco_decode_agent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AgentInfo(
      secret: dco_decode_String(arr[0]),
      subject: dco_decode_String(arr[1]),
      publicKey: dco_decode_String(arr[2]),
      name: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  AgentInfo dco_decode_box_autoadd_agent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_agent_info(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  MealEstimate dco_decode_box_autoadd_meal_estimate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_meal_estimate(raw);
  }

  @protected
  MealItem dco_decode_box_autoadd_meal_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_meal_item(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MealItem> dco_decode_list_meal_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_meal_item).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VersionMetadata> dco_decode_list_version_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_version_metadata).toList();
  }

  @protected
  MealEstimate dco_decode_meal_estimate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MealEstimate(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      calories: dco_decode_i_64(arr[2]),
      caloriesMin: dco_decode_opt_box_autoadd_i_64(arr[3]),
      caloriesMax: dco_decode_opt_box_autoadd_i_64(arr[4]),
      confidence: dco_decode_String(arr[5]),
      model: dco_decode_String(arr[6]),
      clarifyingQuestion: dco_decode_String(arr[7]),
      proteinGrams: dco_decode_opt_box_autoadd_f_64(arr[8]),
      carbsGrams: dco_decode_opt_box_autoadd_f_64(arr[9]),
      fatGrams: dco_decode_opt_box_autoadd_f_64(arr[10]),
    );
  }

  @protected
  MealItem dco_decode_meal_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return MealItem(
      subject: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      notes: dco_decode_String(arr[3]),
      consumedAtMs: dco_decode_i_64(arr[4]),
      status: dco_decode_String(arr[5]),
      calories: dco_decode_opt_box_autoadd_i_64(arr[6]),
      caloriesMin: dco_decode_opt_box_autoadd_i_64(arr[7]),
      caloriesMax: dco_decode_opt_box_autoadd_i_64(arr[8]),
      imagePath: dco_decode_String(arr[9]),
      confidence: dco_decode_String(arr[10]),
      estimatedByModel: dco_decode_String(arr[11]),
      clarifyingQuestion: dco_decode_String(arr[12]),
      proteinGrams: dco_decode_opt_box_autoadd_f_64(arr[13]),
      carbsGrams: dco_decode_opt_box_autoadd_f_64(arr[14]),
      fatGrams: dco_decode_opt_box_autoadd_f_64(arr[15]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AgentInfo? dco_decode_opt_box_autoadd_agent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_agent_info(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  MealItem? dco_decode_opt_box_autoadd_meal_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_meal_item(raw);
  }

  @protected
  SetupResult dco_decode_setup_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SetupResult(
      agentSecret: dco_decode_String(arr[0]),
      agentSubject: dco_decode_String(arr[1]),
      driveSubject: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VersionMetadata dco_decode_version_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VersionMetadata(
      id: dco_decode_list_prim_u_8_strict(arr[0]),
      timestamp: dco_decode_i_64(arr[1]),
      peerId: dco_decode_String(arr[2]),
      lamport: dco_decode_u_64(arr[3]),
      len: dco_decode_i_32(arr[4]),
      message: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentInfo sse_decode_agent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secret = sse_decode_String(deserializer);
    var var_subject = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    return AgentInfo(
        secret: var_secret,
        subject: var_subject,
        publicKey: var_publicKey,
        name: var_name);
  }

  @protected
  AgentInfo sse_decode_box_autoadd_agent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_agent_info(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  MealEstimate sse_decode_box_autoadd_meal_estimate(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_meal_estimate(deserializer));
  }

  @protected
  MealItem sse_decode_box_autoadd_meal_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_meal_item(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MealItem> sse_decode_list_meal_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MealItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_meal_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VersionMetadata> sse_decode_list_version_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VersionMetadata>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_version_metadata(deserializer));
    }
    return ans_;
  }

  @protected
  MealEstimate sse_decode_meal_estimate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_calories = sse_decode_i_64(deserializer);
    var var_caloriesMin = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_caloriesMax = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_confidence = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_clarifyingQuestion = sse_decode_String(deserializer);
    var var_proteinGrams = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_carbsGrams = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_fatGrams = sse_decode_opt_box_autoadd_f_64(deserializer);
    return MealEstimate(
        name: var_name,
        description: var_description,
        calories: var_calories,
        caloriesMin: var_caloriesMin,
        caloriesMax: var_caloriesMax,
        confidence: var_confidence,
        model: var_model,
        clarifyingQuestion: var_clarifyingQuestion,
        proteinGrams: var_proteinGrams,
        carbsGrams: var_carbsGrams,
        fatGrams: var_fatGrams);
  }

  @protected
  MealItem sse_decode_meal_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_subject = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_consumedAtMs = sse_decode_i_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_calories = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_caloriesMin = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_caloriesMax = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_imagePath = sse_decode_String(deserializer);
    var var_confidence = sse_decode_String(deserializer);
    var var_estimatedByModel = sse_decode_String(deserializer);
    var var_clarifyingQuestion = sse_decode_String(deserializer);
    var var_proteinGrams = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_carbsGrams = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_fatGrams = sse_decode_opt_box_autoadd_f_64(deserializer);
    return MealItem(
        subject: var_subject,
        name: var_name,
        description: var_description,
        notes: var_notes,
        consumedAtMs: var_consumedAtMs,
        status: var_status,
        calories: var_calories,
        caloriesMin: var_caloriesMin,
        caloriesMax: var_caloriesMax,
        imagePath: var_imagePath,
        confidence: var_confidence,
        estimatedByModel: var_estimatedByModel,
        clarifyingQuestion: var_clarifyingQuestion,
        proteinGrams: var_proteinGrams,
        carbsGrams: var_carbsGrams,
        fatGrams: var_fatGrams);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AgentInfo? sse_decode_opt_box_autoadd_agent_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_agent_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MealItem? sse_decode_opt_box_autoadd_meal_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_meal_item(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SetupResult sse_decode_setup_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_agentSecret = sse_decode_String(deserializer);
    var var_agentSubject = sse_decode_String(deserializer);
    var var_driveSubject = sse_decode_String(deserializer);
    return SetupResult(
        agentSecret: var_agentSecret,
        agentSubject: var_agentSubject,
        driveSubject: var_driveSubject);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VersionMetadata sse_decode_version_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_list_prim_u_8_strict(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_peerId = sse_decode_String(deserializer);
    var var_lamport = sse_decode_u_64(deserializer);
    var var_len = sse_decode_i_32(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    return VersionMetadata(
        id: var_id,
        timestamp: var_timestamp,
        peerId: var_peerId,
        lamport: var_lamport,
        len: var_len,
        message: var_message);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_info(AgentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secret, serializer);
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_opt_String(self.name, serializer);
  }

  @protected
  void sse_encode_box_autoadd_agent_info(
      AgentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_agent_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_meal_estimate(
      MealEstimate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_meal_estimate(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_meal_item(
      MealItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_meal_item(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_meal_item(
      List<MealItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_meal_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_version_metadata(
      List<VersionMetadata> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_version_metadata(item, serializer);
    }
  }

  @protected
  void sse_encode_meal_estimate(MealEstimate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_i_64(self.calories, serializer);
    sse_encode_opt_box_autoadd_i_64(self.caloriesMin, serializer);
    sse_encode_opt_box_autoadd_i_64(self.caloriesMax, serializer);
    sse_encode_String(self.confidence, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.clarifyingQuestion, serializer);
    sse_encode_opt_box_autoadd_f_64(self.proteinGrams, serializer);
    sse_encode_opt_box_autoadd_f_64(self.carbsGrams, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fatGrams, serializer);
  }

  @protected
  void sse_encode_meal_item(MealItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_i_64(self.consumedAtMs, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_box_autoadd_i_64(self.calories, serializer);
    sse_encode_opt_box_autoadd_i_64(self.caloriesMin, serializer);
    sse_encode_opt_box_autoadd_i_64(self.caloriesMax, serializer);
    sse_encode_String(self.imagePath, serializer);
    sse_encode_String(self.confidence, serializer);
    sse_encode_String(self.estimatedByModel, serializer);
    sse_encode_String(self.clarifyingQuestion, serializer);
    sse_encode_opt_box_autoadd_f_64(self.proteinGrams, serializer);
    sse_encode_opt_box_autoadd_f_64(self.carbsGrams, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fatGrams, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_agent_info(
      AgentInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_agent_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_meal_item(
      MealItem? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_meal_item(self, serializer);
    }
  }

  @protected
  void sse_encode_setup_result(SetupResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.agentSecret, serializer);
    sse_encode_String(self.agentSubject, serializer);
    sse_encode_String(self.driveSubject, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_version_metadata(
      VersionMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.id, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_String(self.peerId, serializer);
    sse_encode_u_64(self.lamport, serializer);
    sse_encode_i_32(self.len, serializer);
    sse_encode_opt_String(self.message, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
