// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1158615256;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_atomiccanvas_flutter',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  AgentInfo crateApiSimpleAgentFromSecret({required String secret});

  Future<String> crateApiSimpleConnect(
      {required String serverUrl, required String agentSecret});

  AgentInfo crateApiSimpleCreateAgent({required String name});

  Future<String> crateApiSimpleCreateCanvas({required String name});

  Future<String> crateApiSimpleCreateDrive({required String name});

  Future<String> crateApiSimpleCreateResource(
      {required String parentSubject, required String name});

  Future<void> crateApiSimpleDeleteCanvas({required String subject});

  Future<AgentInfo?> crateApiSimpleGetActiveAgent();

  String? crateApiSimpleGetDrive();

  Future<String> crateApiSimpleGetProperty(
      {required String subject, required String property});

  Future<void> crateApiSimpleInitApp();

  Future<List<CanvasListItem>> crateApiSimpleListCanvases();

  Future<List<String>> crateApiSimpleListDrives();

  Future<String> crateApiSimpleLoadAgent({required String secret});

  Future<String> crateApiSimpleLoadCanvasStrokes({required String subject});

  Future<void> crateApiSimpleOpenDb({required String path});

  Future<void> crateApiSimpleRenameCanvas(
      {required String subject, required String name});

  void crateApiSimpleSetDrive({required String subject});

  Future<void> crateApiSimpleSetProperty(
      {required String subject,
      required String property,
      required String value});

  Future<SetupResult> crateApiSimpleSetup({required String name});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  AgentInfo crateApiSimpleAgentFromSecret({required String secret}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(secret, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_agent_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleAgentFromSecretConstMeta,
      argValues: [secret],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleAgentFromSecretConstMeta =>
      const TaskConstMeta(
        debugName: "agent_from_secret",
        argNames: ["secret"],
      );

  @override
  Future<String> crateApiSimpleConnect(
      {required String serverUrl, required String agentSecret}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(serverUrl, serializer);
        sse_encode_String(agentSecret, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleConnectConstMeta,
      argValues: [serverUrl, agentSecret],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleConnectConstMeta => const TaskConstMeta(
        debugName: "connect",
        argNames: ["serverUrl", "agentSecret"],
      );

  @override
  AgentInfo crateApiSimpleCreateAgent({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_agent_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCreateAgentConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCreateAgentConstMeta => const TaskConstMeta(
        debugName: "create_agent",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiSimpleCreateCanvas({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCreateCanvasConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCreateCanvasConstMeta => const TaskConstMeta(
        debugName: "create_canvas",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiSimpleCreateDrive({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCreateDriveConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCreateDriveConstMeta => const TaskConstMeta(
        debugName: "create_drive",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiSimpleCreateResource(
      {required String parentSubject, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(parentSubject, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleCreateResourceConstMeta,
      argValues: [parentSubject, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCreateResourceConstMeta =>
      const TaskConstMeta(
        debugName: "create_resource",
        argNames: ["parentSubject", "name"],
      );

  @override
  Future<void> crateApiSimpleDeleteCanvas({required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleDeleteCanvasConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleDeleteCanvasConstMeta => const TaskConstMeta(
        debugName: "delete_canvas",
        argNames: ["subject"],
      );

  @override
  Future<AgentInfo?> crateApiSimpleGetActiveAgent() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_agent_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetActiveAgentConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetActiveAgentConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_agent",
        argNames: [],
      );

  @override
  String? crateApiSimpleGetDrive() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGetDriveConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetDriveConstMeta => const TaskConstMeta(
        debugName: "get_drive",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleGetProperty(
      {required String subject, required String property}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_String(property, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleGetPropertyConstMeta,
      argValues: [subject, property],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetPropertyConstMeta => const TaskConstMeta(
        debugName: "get_property",
        argNames: ["subject", "property"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<List<CanvasListItem>> crateApiSimpleListCanvases() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_canvas_list_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleListCanvasesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleListCanvasesConstMeta => const TaskConstMeta(
        debugName: "list_canvases",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiSimpleListDrives() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleListDrivesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleListDrivesConstMeta => const TaskConstMeta(
        debugName: "list_drives",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleLoadAgent({required String secret}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(secret, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleLoadAgentConstMeta,
      argValues: [secret],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleLoadAgentConstMeta => const TaskConstMeta(
        debugName: "load_agent",
        argNames: ["secret"],
      );

  @override
  Future<String> crateApiSimpleLoadCanvasStrokes({required String subject}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleLoadCanvasStrokesConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleLoadCanvasStrokesConstMeta =>
      const TaskConstMeta(
        debugName: "load_canvas_strokes",
        argNames: ["subject"],
      );

  @override
  Future<void> crateApiSimpleOpenDb({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleOpenDbConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleOpenDbConstMeta => const TaskConstMeta(
        debugName: "open_db",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiSimpleRenameCanvas(
      {required String subject, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleRenameCanvasConstMeta,
      argValues: [subject, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleRenameCanvasConstMeta => const TaskConstMeta(
        debugName: "rename_canvas",
        argNames: ["subject", "name"],
      );

  @override
  void crateApiSimpleSetDrive({required String subject}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleSetDriveConstMeta,
      argValues: [subject],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetDriveConstMeta => const TaskConstMeta(
        debugName: "set_drive",
        argNames: ["subject"],
      );

  @override
  Future<void> crateApiSimpleSetProperty(
      {required String subject,
      required String property,
      required String value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(subject, serializer);
        sse_encode_String(property, serializer);
        sse_encode_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSetPropertyConstMeta,
      argValues: [subject, property, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetPropertyConstMeta => const TaskConstMeta(
        debugName: "set_property",
        argNames: ["subject", "property", "value"],
      );

  @override
  Future<SetupResult> crateApiSimpleSetup({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_setup_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleSetupConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetupConstMeta => const TaskConstMeta(
        debugName: "setup",
        argNames: ["name"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentInfo dco_decode_agent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AgentInfo(
      secret: dco_decode_String(arr[0]),
      subject: dco_decode_String(arr[1]),
      publicKey: dco_decode_String(arr[2]),
      name: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  AgentInfo dco_decode_box_autoadd_agent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_agent_info(raw);
  }

  @protected
  CanvasListItem dco_decode_canvas_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CanvasListItem(
      subject: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CanvasListItem> dco_decode_list_canvas_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_canvas_list_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AgentInfo? dco_decode_opt_box_autoadd_agent_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_agent_info(raw);
  }

  @protected
  SetupResult dco_decode_setup_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SetupResult(
      agentSecret: dco_decode_String(arr[0]),
      agentSubject: dco_decode_String(arr[1]),
      driveSubject: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentInfo sse_decode_agent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secret = sse_decode_String(deserializer);
    var var_subject = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    return AgentInfo(
        secret: var_secret,
        subject: var_subject,
        publicKey: var_publicKey,
        name: var_name);
  }

  @protected
  AgentInfo sse_decode_box_autoadd_agent_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_agent_info(deserializer));
  }

  @protected
  CanvasListItem sse_decode_canvas_list_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_subject = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return CanvasListItem(subject: var_subject, name: var_name);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CanvasListItem> sse_decode_list_canvas_list_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CanvasListItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_canvas_list_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AgentInfo? sse_decode_opt_box_autoadd_agent_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_agent_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SetupResult sse_decode_setup_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_agentSecret = sse_decode_String(deserializer);
    var var_agentSubject = sse_decode_String(deserializer);
    var var_driveSubject = sse_decode_String(deserializer);
    return SetupResult(
        agentSecret: var_agentSecret,
        agentSubject: var_agentSubject,
        driveSubject: var_driveSubject);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_info(AgentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secret, serializer);
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_opt_String(self.name, serializer);
  }

  @protected
  void sse_encode_box_autoadd_agent_info(
      AgentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_agent_info(self, serializer);
  }

  @protected
  void sse_encode_canvas_list_item(
      CanvasListItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_canvas_list_item(
      List<CanvasListItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_canvas_list_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_agent_info(
      AgentInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_agent_info(self, serializer);
    }
  }

  @protected
  void sse_encode_setup_result(SetupResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.agentSecret, serializer);
    sse_encode_String(self.agentSubject, serializer);
    sse_encode_String(self.driveSubject, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
