// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `find_meals_container`

/// Find the meals container under the active drive, creating it the first time.
/// Idempotent — call it on every launch.
///
/// It is identified by name under the drive, not by a subject remembered on
/// this device: sign in on a second phone and the drive arrives by sync with
/// its container already in it, having never run onboarding here. Looking it up
/// is what keeps that phone from minting a rival container its meals would
/// disappear into.
///
/// If two devices each made one before they ever met, the sort makes both sides
/// pick the same survivor instead of disagreeing forever. Meals already written
/// to the other one are not moved — Phase 2 owns that, once there are meals.
Future<String> ensureMealsContainer() =>
    RustLib.instance.api.crateApiMealsEnsureMealsContainer();
