// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear`, `collect_meals`, `confidence_subject`, `find_meals_container`, `float_prop`, `int_prop`, `read_meal`, `set`, `status_subject`, `string_prop`, `tag_shortname`, `tag_subject`

/// Find the meals container under the active drive, creating it the first time.
/// Idempotent — call it on every launch.
///
/// It is identified by name under the drive, not by a subject remembered on
/// this device: sign in on a second phone and the drive arrives by sync with
/// its container already in it, having never run onboarding here. Looking it up
/// is what keeps that phone from minting a rival container its meals would
/// disappear into.
///
/// If two devices each made one before they ever met, the sort makes both sides
/// pick the same survivor instead of disagreeing forever. Meals already written
/// to the other one are not moved — Phase 2 owns that, once there are meals.
Future<String> ensureMealsContainer() =>
    RustLib.instance.api.crateApiMealsEnsureMealsContainer();

/// Log a meal under the meals container. Returns its subject.
///
/// `calories` decides the status, because those are the same fact: a meal
/// somebody typed a number for is `confirmed` — a human said so, and no
/// estimator should overwrite it — while one without a number is `pending`,
/// which is exactly the queue Phase 4's estimator drains.
Future<String> createMeal(
        {required PlatformInt64 consumedAtMs,
        required String name,
        required String description,
        required String imagePath,
        PlatformInt64? calories}) =>
    RustLib.instance.api.crateApiMealsCreateMeal(
        consumedAtMs: consumedAtMs,
        name: name,
        description: description,
        imagePath: imagePath,
        calories: calories);

/// Correct a meal by hand. `None` leaves a field as it was.
///
/// Typing a calorie count is a confirmation, so it moves the meal to
/// `confirmed` — otherwise Phase 4's estimator would find a `pending` meal the
/// user had already answered and overwrite the answer.
Future<void> updateMeal(
        {required String subject,
        String? name,
        String? description,
        PlatformInt64? calories}) =>
    RustLib.instance.api.crateApiMealsUpdateMeal(
        subject: subject,
        name: name,
        description: description,
        calories: calories);

/// Move a meal to another status. See [`MEAL_STATUSES`].
Future<void> setMealStatus({required String subject, required String status}) =>
    RustLib.instance.api
        .crateApiMealsSetMealStatus(subject: subject, status: status);

/// Write an estimate onto a meal, moving it to `estimated` or `needs-info`.
///
/// **A `confirmed` meal is left alone.** Confirmed means a human typed the
/// number, and the estimate racing it — the user correcting a meal while its
/// call was in flight — must not win. Silently, and returning Ok: it is a race
/// between two correct behaviours, not a mistake anybody made.
Future<void> updateMealEstimate(
        {required String subject, required MealEstimate estimate}) =>
    RustLib.instance.api
        .crateApiMealsUpdateMealEstimate(subject: subject, estimate: estimate);

/// Meals eaten in `[from_ms, to_ms)`, newest first.
///
/// Half-open on purpose: a day is `[midnight, next midnight)`, so a meal at
/// exactly 00:00 belongs to the day starting then and to only one day. Both
/// bounds are UTC milliseconds — the caller works out where its local midnights
/// fall, because the device knows its timezone and its DST and the store does
/// not.
Future<List<MealItem>> listMeals(
        {required PlatformInt64 fromMs, required PlatformInt64 toMs}) =>
    RustLib.instance.api.crateApiMealsListMeals(fromMs: fromMs, toMs: toMs);

/// The meals nobody has put a number on yet, oldest first.
///
/// The estimator's work queue. `estimating` is in it as well as `pending`,
/// because the only thing that ever sets it is an estimate running in this
/// process: a meal still marked `estimating` at launch is one an app that was
/// killed mid-call left behind, and leaving it out would strand it there
/// forever. A queue that is draining knows what it currently holds and skips
/// those itself.
///
/// Oldest first, deliberately the opposite of [`list_meals`]: this is a queue,
/// and the meal that has been waiting longest is the one to do next.
Future<List<MealItem>> listPendingMeals() =>
    RustLib.instance.api.crateApiMealsListPendingMeals();

/// What an estimator worked out about a meal.
///
/// A struct rather than the JSON string the plan sketched, for the reason
/// [`MealItem`] is one: FRB generates the Dart class either way, and a field
/// this side and a key spelled slightly differently on the other is the whole
/// category of bug that plumbing avoids. Dart parses the model's JSON already —
/// it has to, to know whether to ask a follow-up question — so nothing is saved
/// by handing the string on.
class MealEstimate {
  final String name;

  /// How the estimator got there. Overwrites what was on the meal, which for
  /// a photographed one is nothing and for a typed one was the user's words —
  /// so this must arrive with those words in it (the caller sends them to the
  /// model in the first place).
  final String description;
  final PlatformInt64 calories;
  final PlatformInt64? caloriesMin;
  final PlatformInt64? caloriesMax;

  /// One of [`ESTIMATE_CONFIDENCES`].
  final String confidence;

  /// The OpenRouter model id, so a number can be traced to what made it.
  final String model;

  /// The one thing the estimator could not tell — "was that milk or oat
  /// milk?". Empty when it was sure enough, and what decides the resulting
  /// status: a question makes the meal `needs-info`, because a meal waiting
  /// on an answer with no question to show is a dead end. Low confidence on
  /// its own is just a wide range, which the bounds already say.
  final String clarifyingQuestion;
  final double? proteinGrams;
  final double? carbsGrams;
  final double? fatGrams;

  const MealEstimate({
    required this.name,
    required this.description,
    required this.calories,
    this.caloriesMin,
    this.caloriesMax,
    required this.confidence,
    required this.model,
    required this.clarifyingQuestion,
    this.proteinGrams,
    this.carbsGrams,
    this.fatGrams,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      calories.hashCode ^
      caloriesMin.hashCode ^
      caloriesMax.hashCode ^
      confidence.hashCode ^
      model.hashCode ^
      clarifyingQuestion.hashCode ^
      proteinGrams.hashCode ^
      carbsGrams.hashCode ^
      fatGrams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MealEstimate &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          calories == other.calories &&
          caloriesMin == other.caloriesMin &&
          caloriesMax == other.caloriesMax &&
          confidence == other.confidence &&
          model == other.model &&
          clarifyingQuestion == other.clarifyingQuestion &&
          proteinGrams == other.proteinGrams &&
          carbsGrams == other.carbsGrams &&
          fatGrams == other.fatGrams;
}

/// One meal, flattened for the Dart side.
///
/// The estimate fields are `Option` rather than zero-defaulted: "nobody has
/// worked out what this was yet" and "this had no calories" are different
/// answers, and a day total that silently counts the first as the second is
/// wrong in the direction that matters.
class MealItem {
  final String subject;
  final String name;
  final String description;

  /// Unix epoch milliseconds, UTC. Which local day that falls in is the
  /// caller's question — see [`list_meals`].
  final PlatformInt64 consumedAtMs;

  /// One of [`MEAL_STATUSES`].
  final String status;
  final PlatformInt64? calories;
  final PlatformInt64? caloriesMin;
  final PlatformInt64? caloriesMax;

  /// Relative to the app documents directory. Empty for typed entries.
  final String imagePath;

  /// `high` · `medium` · `low`, or empty when nothing has estimated it.
  final String confidence;
  final String estimatedByModel;

  /// What the estimator could not tell — set with `needs-info`, empty
  /// otherwise. See [`MealEstimate::clarifying_question`].
  final String clarifyingQuestion;
  final double? proteinGrams;
  final double? carbsGrams;
  final double? fatGrams;

  const MealItem({
    required this.subject,
    required this.name,
    required this.description,
    required this.consumedAtMs,
    required this.status,
    this.calories,
    this.caloriesMin,
    this.caloriesMax,
    required this.imagePath,
    required this.confidence,
    required this.estimatedByModel,
    required this.clarifyingQuestion,
    this.proteinGrams,
    this.carbsGrams,
    this.fatGrams,
  });

  @override
  int get hashCode =>
      subject.hashCode ^
      name.hashCode ^
      description.hashCode ^
      consumedAtMs.hashCode ^
      status.hashCode ^
      calories.hashCode ^
      caloriesMin.hashCode ^
      caloriesMax.hashCode ^
      imagePath.hashCode ^
      confidence.hashCode ^
      estimatedByModel.hashCode ^
      clarifyingQuestion.hashCode ^
      proteinGrams.hashCode ^
      carbsGrams.hashCode ^
      fatGrams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MealItem &&
          runtimeType == other.runtimeType &&
          subject == other.subject &&
          name == other.name &&
          description == other.description &&
          consumedAtMs == other.consumedAtMs &&
          status == other.status &&
          calories == other.calories &&
          caloriesMin == other.caloriesMin &&
          caloriesMax == other.caloriesMax &&
          imagePath == other.imagePath &&
          confidence == other.confidence &&
          estimatedByModel == other.estimatedByModel &&
          clarifyingQuestion == other.clarifyingQuestion &&
          proteinGrams == other.proteinGrams &&
          carbsGrams == other.carbsGrams &&
          fatGrams == other.fatGrams;
}
