// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple/types.dart';

// These functions are ignored because they are not marked as `pub`: `db_event_to_json`, `drive_resource_exists`, `ensure_sync_connectivity`, `is_unreachable_hub_url`, `nudge_peers_after_local_change`, `save_and_push`, `sync_connectivity_inner`, `try_auto_peer_sync`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PeerSyncReport`, `SyncConnectivityReport`

/// Local-first Atomic Data SDK for Flutter.
///
/// API groups:
///   1. Database  — open_db()
///   2. Agent     — setup(), load_agent(), get_active_agent(), clear_agent()
///   3. Drive     — create_drive(), list_drives(), get_active_drive(), set_active_drive()
///   4. Resource  — create_resource(), set_property(), get_property(), rename_resource(),
///                  delete_resource()
///   5. History   — warm_resource_history(), get_resource_history(), get_property_at_version()
///   6. WS sync   — open_ws_sync(), close_ws_sync(), sync_drive_to_server(), resume_app_session()
///   7. Peer      — start_peer(), get_peer_id(), peer_announce(), peer_sync(), peer_discover_sync()
///
/// Networking (groups 6-7) is explicit and opt-in. Nothing in groups 1-5 reaches
/// the network beyond the best-effort push a save makes when a session is open.
///
/// This module is deliberately app-agnostic — no meal, no calorie, nothing this
/// app owns. Meal CRUD lands beside it in Phase 2, so the two can be merged back
/// into one shared crate with the Atomic Canvas bridge later.
/// Open a local database. Call once on app start.
Future<void> openDb({required String path}) =>
    RustLib.instance.api.crateApiSimpleOpenDb(path: path);

/// Create an agent and a personal drive in one call. Pure local — no networking.
/// Call `start_peer()` + `peer_announce()` afterwards if you want to be discoverable.
Future<SetupResult> setup({required String name}) =>
    RustLib.instance.api.crateApiSimpleSetup(name: name);

/// Load an existing agent from a secret. Pure local — no networking.
/// If the secret contains a drive DID, it becomes the active drive.
///
/// Returns "needs_sync" if the drive doesn't exist locally (needs QR pairing).
/// Returns the agent subject if everything is available.
Future<String> loadAgent({required String secret}) =>
    RustLib.instance.api.crateApiSimpleLoadAgent(secret: secret);

/// Get the currently active agent, if any.
Future<AgentInfo?> getActiveAgent() =>
    RustLib.instance.api.crateApiSimpleGetActiveAgent();

/// Clear the active agent.
Future<void> clearAgent() => RustLib.instance.api.crateApiSimpleClearAgent();

AgentInfo createAgent({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateAgent(name: name);

AgentInfo agentFromSecret({required String secret}) =>
    RustLib.instance.api.crateApiSimpleAgentFromSecret(secret: secret);

/// Create a new drive. Returns the drive subject.
Future<String> createDrive({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateDrive(name: name);

/// Get the active drive subject, if one is set.
String? getActiveDrive() => RustLib.instance.api.crateApiSimpleGetActiveDrive();

/// Set the active drive.
Future<void> setActiveDrive({required String subject}) =>
    RustLib.instance.api.crateApiSimpleSetActiveDrive(subject: subject);

/// List drives belonging to the current agent.
Future<List<String>> listDrives() =>
    RustLib.instance.api.crateApiSimpleListDrives();

/// List drives with names. Returns JSON-encoded array of {subject, name}.
Future<String> listDrivesWithNames() =>
    RustLib.instance.api.crateApiSimpleListDrivesWithNames();

/// Create a named child of `parent_subject`.
///
/// `class` is the `is-a` subject the resource gets, and it is not optional
/// decoration: `create_resource` validates the new resource against it, so a
/// class whose required properties aren't being set here fails the write. The
/// canvas bridge hardcoded `urls::CLASS` — the meta-class used to *define*
/// classes, which requires a `shortname` — and every call through it failed;
/// nothing called it, so nobody found out. Pass [`atomic_lib::urls::FOLDER`]
/// for a plain container, or an app class once its ontology is seeded.
Future<String> createResource(
        {required String parentSubject,
        required String name,
        required String class_}) =>
    RustLib.instance.api.crateApiSimpleCreateResource(
        parentSubject: parentSubject, name: name, class_: class_);

Future<void> setProperty(
        {required String subject,
        required String property,
        required String value}) =>
    RustLib.instance.api.crateApiSimpleSetProperty(
        subject: subject, property: property, value: value);

Future<String> getProperty(
        {required String subject, required String property}) =>
    RustLib.instance.api
        .crateApiSimpleGetProperty(subject: subject, property: property);

/// Rename any resource (sets the core `name` property).
Future<void> renameResource({required String subject, required String name}) =>
    RustLib.instance.api
        .crateApiSimpleRenameResource(subject: subject, name: name);

/// Delete a resource with a signed destroy commit, pushed over WS / Iroh.
Future<void> deleteResource({required String subject}) =>
    RustLib.instance.api.crateApiSimpleDeleteResource(subject: subject);

/// Load versioned state for history operations.
Future<void> warmResourceHistory({required String subject}) =>
    RustLib.instance.api.crateApiSimpleWarmResourceHistory(subject: subject);

/// Get the edit history of a resource.
Future<List<VersionMetadata>> getResourceHistory({required String subject}) =>
    RustLib.instance.api.crateApiSimpleGetResourceHistory(subject: subject);

/// Read one property as it stood at a historical version.
///
/// Generic where the canvas bridge's twin was stroke-specific: an app whose
/// resources have no single "the content" property has to name the one it wants.
Future<String> getPropertyAtVersion(
        {required String subject,
        required List<int> versionId,
        required String property}) =>
    RustLib.instance.api.crateApiSimpleGetPropertyAtVersion(
        subject: subject, versionId: versionId, property: property);

/// Open a WebSocket sync session to an Atomic Server. Authenticates, SUBs the active drive,
/// and applies incoming UPDATE / QUERY_UPDATE / COMMIT frames to the local DB.
Future<void> openWsSync({required String serverUrl}) =>
    RustLib.instance.api.crateApiSimpleOpenWsSync(serverUrl: serverUrl);

/// Close the WebSocket sync session.
Future<void> closeWsSync() => RustLib.instance.api.crateApiSimpleCloseWsSync();

/// Push the active drive to a server, so it is hosted there as well as here.
///
/// [`open_ws_sync`] fetches a drive this device lacks, and pushes commits made
/// from now on — but a drive made here before any server was connected has
/// never been offered to one. This offers it: the same replication
/// `/replicate-drive` runs, signed as this device's agent, which is the drive's
/// owner and so may write it at the remote.
///
/// Returns the number of resources pushed.
Future<int> syncDriveToServer({required String serverUrl}) =>
    RustLib.instance.api.crateApiSimpleSyncDriveToServer(serverUrl: serverUrl);

/// Restore agent + drive on app start. Opens WS sync, fetches drive from server when
/// missing. Returns `"ok"` or `"needs_sync"`.
Future<String> resumeAppSession(
        {required String serverUrl,
        required String secret,
        String? driveHint}) =>
    RustLib.instance.api.crateApiSimpleResumeAppSession(
        serverUrl: serverUrl, secret: secret, driveHint: driveHint);

/// Start Iroh, sync known peers (then pkarr). Returns JSON [`SyncConnectivityReport`].
Future<String> syncConnectivityNow() =>
    RustLib.instance.api.crateApiSimpleSyncConnectivityNow();

/// Subscribe to live updates for a single resource over WebSocket.
Future<void> wsSubscribeResource({required String subject}) =>
    RustLib.instance.api.crateApiSimpleWsSubscribeResource(subject: subject);

/// Block until a local DB event arrives. Returns JSON, or None on timeout.
Future<String?> pollDbEvent({required int timeoutMs}) =>
    RustLib.instance.api.crateApiSimplePollDbEvent(timeoutMs: timeoutMs);

/// Start the Iroh peer node. Returns the NodeID.
/// Call this before any sync operations.
Future<String> startPeer() => RustLib.instance.api.crateApiSimpleStartPeer();

/// Get this device's Iroh NodeID (if peer is running).
String? getPeerId() => RustLib.instance.api.crateApiSimpleGetPeerId();

/// Announce this device for a drive via pkarr relay.
/// Publishes the Iroh NodeID so other devices can discover and connect.
Future<void> peerAnnounce({required String driveSubject}) =>
    RustLib.instance.api.crateApiSimplePeerAnnounce(driveSubject: driveSubject);

/// Sync the active drive with a specific peer by Iroh NodeID.
/// Call `start_peer()` first.
Future<String> peerSync({required String nodeId}) =>
    RustLib.instance.api.crateApiSimplePeerSync(nodeId: nodeId);

/// Discover a peer for a drive via pkarr relay and sync. Call `start_peer()` first.
/// Prefer [`sync_connectivity_now`] — tries known peers first, returns clearer errors.
Future<int> peerDiscoverSync({required String driveSubject}) =>
    RustLib.instance.api
        .crateApiSimplePeerDiscoverSync(driveSubject: driveSubject);

/// Get all known peers as JSON: [{"node_id":"...","name":"..."},...]
String getKnownPeers() => RustLib.instance.api.crateApiSimpleGetKnownPeers();

/// Same as [`get_known_peers`] — the name the Dart client calls.
String getKnownPeersJson() =>
    RustLib.instance.api.crateApiSimpleGetKnownPeersJson();

/// Add a peer with optional name.
void addKnownPeer({required String nodeId, required String name}) =>
    RustLib.instance.api.crateApiSimpleAddKnownPeer(nodeId: nodeId, name: name);

/// Remove a peer by NodeID.
void removeKnownPeer({required String nodeId}) =>
    RustLib.instance.api.crateApiSimpleRemoveKnownPeer(nodeId: nodeId);

String getDeviceName() => RustLib.instance.api.crateApiSimpleGetDeviceName();

void setDeviceName({required String name}) =>
    RustLib.instance.api.crateApiSimpleSetDeviceName(name: name);

int livePeerCount() => RustLib.instance.api.crateApiSimpleLivePeerCount();

List<String> livePeerIds() => RustLib.instance.api.crateApiSimpleLivePeerIds();

Future<int> waitForPeerCountChange({required int current}) =>
    RustLib.instance.api.crateApiSimpleWaitForPeerCountChange(current: current);

Future<String> pollSyncEvents() =>
    RustLib.instance.api.crateApiSimplePollSyncEvents();

Future<String> waitForSyncEvent() =>
    RustLib.instance.api.crateApiSimpleWaitForSyncEvent();

Future<String> watchResource({required String subject}) =>
    RustLib.instance.api.crateApiSimpleWatchResource(subject: subject);

Future<String> watchChildren({required String parent}) =>
    RustLib.instance.api.crateApiSimpleWatchChildren(parent: parent);
