// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.
//
// NOTE: Some functions below are manually added (marked with TODO: codegen).
// They will be replaced when flutter_rust_bridge codegen runs next.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dart:typed_data';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// ── 1. Database ────────────────────────────────────────────────────────────

/// Open a local database. Call once on app start.
Future<void> openDb({required String path}) =>
    RustLib.instance.api.crateApiSimpleOpenDb(path: path);

// ── 2. Agent ───────────────────────────────────────────────────────────────

/// Create an agent and a personal drive. Pure local — no networking.
Future<SetupResult> setup({required String name}) =>
    RustLib.instance.api.crateApiSimpleSetup(name: name);

/// Load an existing agent from a secret. Pure local — no networking.
Future<String> loadAgent({required String secret}) =>
    RustLib.instance.api.crateApiSimpleLoadAgent(secret: secret);

/// Get the currently active agent, if any.
Future<AgentInfo?> getActiveAgent() =>
    RustLib.instance.api.crateApiSimpleGetActiveAgent();

/// Clear the active agent.
// TODO: codegen — clearAgent is new, needs FRB codegen to generate the dispatcher.
// For now, call via the legacy bridge or handle in the wrapper.
void clearAgent() {
  // Will be: RustLib.instance.api.crateApiSimpleClearAgent();
  throw UnimplementedError('clearAgent: awaiting FRB codegen');
}

AgentInfo createAgent({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateAgent(name: name);

AgentInfo agentFromSecret({required String secret}) =>
    RustLib.instance.api.crateApiSimpleAgentFromSecret(secret: secret);

Future<String> connect(
        {required String serverUrl, required String agentSecret}) =>
    RustLib.instance.api
        .crateApiSimpleConnect(serverUrl: serverUrl, agentSecret: agentSecret);

// ── 3. Drive ───────────────────────────────────────────────────────────────

/// Create a new drive. Returns the drive subject.
Future<String> createDrive({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateDrive(name: name);

/// Get the active drive subject, if one is set.
// TODO: codegen — getActiveDrive is new (renamed from getDrive).
// The FRB dispatcher still uses the old name. Alias for now.
String? getActiveDrive() => RustLib.instance.api.crateApiSimpleGetDrive();

/// Set the active drive.
// TODO: codegen — setActiveDrive is new (renamed from setDrive).
void setActiveDrive({required String subject}) =>
    RustLib.instance.api.crateApiSimpleSetDrive(subject: subject);

/// List drives belonging to the current agent.
Future<List<String>> listDrives() =>
    RustLib.instance.api.crateApiSimpleListDrives();

// ── 4. Resource ────────────────────────────────────────────────────────────

Future<String> createResource(
        {required String parentSubject, required String name}) =>
    RustLib.instance.api
        .crateApiSimpleCreateResource(parentSubject: parentSubject, name: name);

Future<void> setProperty(
        {required String subject,
        required String property,
        required String value}) =>
    RustLib.instance.api.crateApiSimpleSetProperty(
        subject: subject, property: property, value: value);

Future<String> getProperty(
        {required String subject, required String property}) =>
    RustLib.instance.api
        .crateApiSimpleGetProperty(subject: subject, property: property);

// ── 5. Canvas CRUD ─────────────────────────────────────────────────────────

Future<String> createCanvas({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateCanvas(name: name);

Future<String> loadCanvasStrokes({required String subject}) =>
    RustLib.instance.api.crateApiSimpleLoadCanvasStrokes(subject: subject);

Future<List<CanvasListItem>> listCanvases() =>
    RustLib.instance.api.crateApiSimpleListCanvases();

Future<void> deleteCanvas({required String subject}) =>
    RustLib.instance.api.crateApiSimpleDeleteCanvas(subject: subject);

Future<void> renameCanvas({required String subject, required String name}) =>
    RustLib.instance.api
        .crateApiSimpleRenameCanvas(subject: subject, name: name);

// ── 6. History ─────────────────────────────────────────────────────────────
// TODO: codegen — these are new functions, need FRB codegen.

Future<void> warmResourceHistory({required String subject}) {
  throw UnimplementedError('warmResourceHistory: awaiting FRB codegen');
}

Future<List<VersionMetadata>> getResourceHistory({required String subject}) {
  throw UnimplementedError('getResourceHistory: awaiting FRB codegen');
}

Future<String> getResourceAtVersion(
    {required String subject, required Uint8List versionId}) {
  throw UnimplementedError('getResourceAtVersion: awaiting FRB codegen');
}

// ── 7. Peer / Sync (explicit, opt-in) ─────────────────────────────────────
// TODO: codegen — these are new functions, need FRB codegen.

// Peer/sync functions route through the legacy `connect` bridge until FRB codegen runs.
// The Rust `connect` dispatches based on the first argument.

/// Start the Iroh peer node. Returns the NodeID. Call before any sync.
Future<String> startPeer() => connect(serverUrl: 'start_peer', agentSecret: '');

/// Get this device's Iroh NodeID, or null if peer not started.
/// Note: this goes through an async bridge because the sync bridge isn't available.
Future<String?> getPeerId() async {
  final result = await connect(serverUrl: 'get_peer_id', agentSecret: '');
  return result.isEmpty ? null : result;
}

/// Announce a drive on the DHT. If Iroh is running, publishes NodeID too.
Future<void> peerAnnounce({required String driveSubject}) async {
  await connect(serverUrl: 'announce', agentSecret: '');
}

/// Sync the active drive with a specific peer by NodeID.
Future<int> peerSync({required String nodeId}) async {
  final result = await connect(serverUrl: nodeId, agentSecret: '');
  return int.tryParse(result.replaceAll(RegExp(r'[^0-9]'), '')) ?? 0;
}

/// Discover a peer for a drive via DHT and sync. Combines lookup + sync.
Future<int> peerDiscoverSync({required String driveSubject}) async {
  final result = await connect(serverUrl: 'discover_sync', agentSecret: '');
  return int.tryParse(result) ?? 0;
}

// ── Data classes ───────────────────────────────────────────────────────────

class VersionMetadata {
  final Uint8List id;
  final int timestamp;
  final String peerId;
  final int lamport;
  final int len;
  final String? message;

  const VersionMetadata({
    required this.id,
    required this.timestamp,
    required this.peerId,
    required this.lamport,
    required this.len,
    this.message,
  });
}

class AgentInfo {
  final String secret;
  final String subject;
  final String publicKey;
  final String? name;

  const AgentInfo({
    required this.secret,
    required this.subject,
    required this.publicKey,
    this.name,
  });

  @override
  int get hashCode =>
      secret.hashCode ^ subject.hashCode ^ publicKey.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentInfo &&
          runtimeType == other.runtimeType &&
          secret == other.secret &&
          subject == other.subject &&
          publicKey == other.publicKey &&
          name == other.name;
}

class CanvasListItem {
  final String subject;
  final String name;

  const CanvasListItem({
    required this.subject,
    required this.name,
  });

  @override
  int get hashCode => subject.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CanvasListItem &&
          runtimeType == other.runtimeType &&
          subject == other.subject &&
          name == other.name;
}

class SetupResult {
  final String agentSecret;
  final String agentSubject;
  final String driveSubject;

  const SetupResult({
    required this.agentSecret,
    required this.agentSubject,
    required this.driveSubject,
  });

  @override
  int get hashCode =>
      agentSecret.hashCode ^ agentSubject.hashCode ^ driveSubject.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetupResult &&
          runtimeType == other.runtimeType &&
          agentSecret == other.agentSecret &&
          agentSubject == other.agentSubject &&
          driveSubject == other.driveSubject;
}
