// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple/types.dart';

// These functions are ignored because they are not marked as `pub`: `canvas_entry`, `db_event_to_json`, `destroy_resource_and_sync`, `drive_resource_exists`, `ensure_cache_listener`, `ensure_sync_connectivity`, `get_canvas`, `is_unreachable_hub_url`, `nudge_peers_after_local_change`, `save_and_push`, `sync_connectivity_inner`, `try_auto_peer_sync`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SyncConnectivityReport`

/// Local-first Atomic Data SDK for Flutter.
///
/// API groups:
///   1. Database  — open_db()
///   2. Agent     — setup(), load_agent(), get_active_agent(), clear_agent()
///   3. Drive     — create_drive(), list_drives(), get_active_drive(), set_active_drive()
///   4. Resource  — create_resource(), set_property(), get_property()
///   5. Canvas    — create_canvas(), save/load/list/delete/rename
///   6. History   — warm_resource_history(), get_resource_history(), get_resource_at_version()
///   7. Peer      — start_peer(), get_peer_id(), peer_announce(), peer_sync(), peer_discover_sync()
///
/// Networking (group 7) is explicit and opt-in. Nothing in groups 1-6 touches the network.
/// Open a local database. Call once on app start.
Future<void> openDb({required String path}) =>
    RustLib.instance.api.crateApiSimpleOpenDb(path: path);

/// Create an agent and a personal drive in one call. Pure local — no networking.
/// Call `start_peer()` + `peer_announce()` afterwards if you want to be discoverable.
Future<SetupResult> setup({required String name}) =>
    RustLib.instance.api.crateApiSimpleSetup(name: name);

/// Load an existing agent from a secret. Pure local — no networking.
/// If the secret contains a drive DID, it becomes the active drive.
///
/// Returns "needs_sync" if the drive doesn't exist locally (needs QR pairing).
/// Returns the agent subject if everything is available.
Future<String> loadAgent({required String secret}) =>
    RustLib.instance.api.crateApiSimpleLoadAgent(secret: secret);

/// Get the currently active agent, if any.
Future<AgentInfo?> getActiveAgent() =>
    RustLib.instance.api.crateApiSimpleGetActiveAgent();

/// Clear the active agent.
Future<void> clearAgent() => RustLib.instance.api.crateApiSimpleClearAgent();

AgentInfo createAgent({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateAgent(name: name);

AgentInfo agentFromSecret({required String secret}) =>
    RustLib.instance.api.crateApiSimpleAgentFromSecret(secret: secret);

/// Create a new drive. Returns the drive subject.
Future<String> createDrive({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateDrive(name: name);

/// Get the active drive subject, if one is set.
String? getActiveDrive() => RustLib.instance.api.crateApiSimpleGetActiveDrive();

/// Set the active drive.
Future<void> setActiveDrive({required String subject}) =>
    RustLib.instance.api.crateApiSimpleSetActiveDrive(subject: subject);

/// List drives belonging to the current agent, with names.
Future<List<String>> listDrives() =>
    RustLib.instance.api.crateApiSimpleListDrives();

/// List drives with names. Returns JSON-encoded array of {subject, name}.
Future<String> listDrivesWithNames() =>
    RustLib.instance.api.crateApiSimpleListDrivesWithNames();

Future<String> createResource(
        {required String parentSubject, required String name}) =>
    RustLib.instance.api
        .crateApiSimpleCreateResource(parentSubject: parentSubject, name: name);

Future<void> setProperty(
        {required String subject,
        required String property,
        required String value}) =>
    RustLib.instance.api.crateApiSimpleSetProperty(
        subject: subject, property: property, value: value);

Future<String> getProperty(
        {required String subject, required String property}) =>
    RustLib.instance.api
        .crateApiSimpleGetProperty(subject: subject, property: property);

/// Create a new canvas. Uses the active drive as parent.
Future<String> createCanvas({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateCanvas(name: name);

/// Create a canvas, optionally in a gallery folder (`folder_id` = folder resource subject).
Future<String> createCanvasWithFolder(
        {required String name, String? folderId}) =>
    RustLib.instance.api
        .crateApiSimpleCreateCanvasWithFolder(name: name, folderId: folderId);

/// Create a folder resource under the active drive.
Future<String> createFolder({required String name}) =>
    RustLib.instance.api.crateApiSimpleCreateFolder(name: name);

/// List folder resources in the active drive.
Future<List<FolderListItem>> listFolders() =>
    RustLib.instance.api.crateApiSimpleListFolders();

/// Set or clear the gallery folder for a canvas (persisted + synced).
Future<void> setCanvasFolder({required String subject, String? folderId}) =>
    RustLib.instance.api
        .crateApiSimpleSetCanvasFolder(subject: subject, folderId: folderId);

/// Push a single stroke to a canvas. Appends to the stroke list; merges across devices.
Future<void> pushStroke(
        {required String subject, required String strokeJson}) =>
    RustLib.instance.api
        .crateApiSimplePushStroke(subject: subject, strokeJson: strokeJson);

/// Load strokes JSON from a canvas. Reads directly from DB (no edit session).
Future<String> loadCanvasStrokes({required String subject}) =>
    RustLib.instance.api.crateApiSimpleLoadCanvasStrokes(subject: subject);

/// List all canvases in the active drive.
/// Uses the query index (not a full scan) so results include synced resources.
Future<List<CanvasListItem>> listCanvases() =>
    RustLib.instance.api.crateApiSimpleListCanvases();

/// List canvases as JSON (includes `folder_id`). Prefer this from Dart until FRB codegen.
Future<String> listCanvasesJson() =>
    RustLib.instance.api.crateApiSimpleListCanvasesJson();

/// Delete a canvas (or any resource) with a signed destroy commit.
Future<void> deleteCanvas({required String subject}) =>
    RustLib.instance.api.crateApiSimpleDeleteCanvas(subject: subject);

/// Rename a canvas.
Future<void> renameCanvas({required String subject, required String name}) =>
    RustLib.instance.api
        .crateApiSimpleRenameCanvas(subject: subject, name: name);

/// Delete a single stroke by index.
Future<void> deleteStroke({required String subject, required int index}) =>
    RustLib.instance.api
        .crateApiSimpleDeleteStroke(subject: subject, index: index);

/// Undo the last edit on a canvas. Returns the new stroke count.
Future<int> undoCanvas({required String subject}) =>
    RustLib.instance.api.crateApiSimpleUndoCanvas(subject: subject);

/// Whether the canvas has a local undo step available.
Future<bool> canUndoCanvas({required String subject}) =>
    RustLib.instance.api.crateApiSimpleCanUndoCanvas(subject: subject);

/// Whether the canvas has a local redo step available.
Future<bool> canRedoCanvas({required String subject}) =>
    RustLib.instance.api.crateApiSimpleCanRedoCanvas(subject: subject);

/// Redo the last undone edit on a canvas. Returns the new stroke count.
Future<int> redoCanvas({required String subject}) =>
    RustLib.instance.api.crateApiSimpleRedoCanvas(subject: subject);

/// Load versioned state for history operations.
Future<void> warmResourceHistory({required String subject}) =>
    RustLib.instance.api.crateApiSimpleWarmResourceHistory(subject: subject);

/// Get the edit history of a resource.
Future<List<VersionMetadata>> getResourceHistory({required String subject}) =>
    RustLib.instance.api.crateApiSimpleGetResourceHistory(subject: subject);

/// Get canvas strokes at a specific historical version.
Future<String> getResourceAtVersion(
        {required String subject, required List<int> versionId}) =>
    RustLib.instance.api.crateApiSimpleGetResourceAtVersion(
        subject: subject, versionId: versionId);

/// Open a WebSocket sync session to an Atomic Server. Authenticates, SUBs the active drive,
/// and applies incoming UPDATE / QUERY_UPDATE / COMMIT frames to the local DB.
Future<void> openWsSync({required String serverUrl}) =>
    RustLib.instance.api.crateApiSimpleOpenWsSync(serverUrl: serverUrl);

/// Close the WebSocket sync session.
Future<void> closeWsSync() => RustLib.instance.api.crateApiSimpleCloseWsSync();

/// Restore agent + drive on app start. Opens WS sync, fetches drive from server when missing,
/// then falls back to Iroh discover / known peers (previous "auto pair on boot" behaviour).
/// Returns `"ok"` or `"needs_sync"`.
Future<String> resumeAppSession(
        {required String serverUrl,
        required String secret,
        String? driveHint}) =>
    RustLib.instance.api.crateApiSimpleResumeAppSession(
        serverUrl: serverUrl, secret: secret, driveHint: driveHint);

/// Start Iroh, sync known peers (then pkarr). Returns JSON [`SyncConnectivityReport`].
Future<String> syncConnectivityNow() =>
    RustLib.instance.api.crateApiSimpleSyncConnectivityNow();

/// Subscribe to live updates for an open canvas over WebSocket.
Future<void> wsSubscribeCanvas({required String subject}) =>
    RustLib.instance.api.crateApiSimpleWsSubscribeCanvas(subject: subject);

/// Block until a local DB event arrives. Returns JSON, or None on timeout.
Future<String?> pollDbEvent({required int timeoutMs}) =>
    RustLib.instance.api.crateApiSimplePollDbEvent(timeoutMs: timeoutMs);

/// Start the Iroh peer node. Returns the NodeID.
/// Call this before any sync operations.
Future<String> startPeer() => RustLib.instance.api.crateApiSimpleStartPeer();

/// Get this device's Iroh NodeID (if peer is running).
String? getPeerId() => RustLib.instance.api.crateApiSimpleGetPeerId();

/// Announce this device for a drive via pkarr relay.
/// Publishes the Iroh NodeID so other devices can discover and connect.
Future<void> peerAnnounce({required String driveSubject}) =>
    RustLib.instance.api.crateApiSimplePeerAnnounce(driveSubject: driveSubject);

/// Sync the active drive with a specific peer by Iroh NodeID.
/// Call `start_peer()` first.
Future<int> peerSync({required String nodeId}) =>
    RustLib.instance.api.crateApiSimplePeerSync(nodeId: nodeId);

/// Discover a peer for a drive via pkarr relay and sync. Call `start_peer()` first.
/// Prefer [`sync_connectivity_now`] — tries known peers first, returns clearer errors.
Future<int> peerDiscoverSync({required String driveSubject}) =>
    RustLib.instance.api
        .crateApiSimplePeerDiscoverSync(driveSubject: driveSubject);

/// Get all known peers as JSON: [{"node_id":"...","name":"..."},...]
String getKnownPeers() => RustLib.instance.api.crateApiSimpleGetKnownPeers();

/// Add a peer with optional name.
void addKnownPeer({required String nodeId, required String name}) =>
    RustLib.instance.api.crateApiSimpleAddKnownPeer(nodeId: nodeId, name: name);

/// Remove a peer by NodeID.
void removeKnownPeer({required String nodeId}) =>
    RustLib.instance.api.crateApiSimpleRemoveKnownPeer(nodeId: nodeId);

void setDrive({required String subject}) =>
    RustLib.instance.api.crateApiSimpleSetDrive(subject: subject);

String? getDrive() => RustLib.instance.api.crateApiSimpleGetDrive();

String getDeviceName() => RustLib.instance.api.crateApiSimpleGetDeviceName();

void setDeviceName({required String name}) =>
    RustLib.instance.api.crateApiSimpleSetDeviceName(name: name);

int livePeerCount() => RustLib.instance.api.crateApiSimpleLivePeerCount();

List<String> livePeerIds() => RustLib.instance.api.crateApiSimpleLivePeerIds();

Future<int> waitForPeerCountChange({required int current}) =>
    RustLib.instance.api.crateApiSimpleWaitForPeerCountChange(current: current);

Future<String> pollSyncEvents() =>
    RustLib.instance.api.crateApiSimplePollSyncEvents();

Future<String> waitForSyncEvent() =>
    RustLib.instance.api.crateApiSimpleWaitForSyncEvent();

Future<String> watchResource({required String subject}) =>
    RustLib.instance.api.crateApiSimpleWatchResource(subject: subject);

Future<String> watchChildren({required String parent}) =>
    RustLib.instance.api.crateApiSimpleWatchChildren(parent: parent);

Future<void> setStrokes(
        {required String subject, required String strokesJson}) =>
    RustLib.instance.api
        .crateApiSimpleSetStrokes(subject: subject, strokesJson: strokesJson);

String getKnownPeersJson() =>
    RustLib.instance.api.crateApiSimpleGetKnownPeersJson();
