#!/usr/bin/env python3
"""Measure hand-written production code in a declared consolidation scope.

See planning/consolidation-contract.md. Typical use:

  scripts/consolidation-measure.py --write /tmp/before.json -- path [path...]
  # ... edit ...
  scripts/consolidation-measure.py --baseline /tmp/before.json -- path [path...]

Exits 1 when --baseline is set and a gate fails (production non-blank lines
did not drop, or max file / public items grew).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

CODE_SUFFIXES = {".rs", ".ts", ".tsx", ".js", ".jsx", ".dart", ".py"}
SKIP_DIR_NAMES = {
    "target",
    "node_modules",
    "dist",
    ".git",
}
TEST_SUFFIXES = {".test.ts", ".test.tsx", ".test.js", ".spec.ts", ".spec.tsx"}
GENERATED_MARKERS = (
    "GENERATED WITH",
    "@generated",
    "auto-generated",
    "Code generated by",
    "flutter_rust_bridge",
)
CFG_TEST_RE = re.compile(r"(?m)^#\[cfg\(test\)\]\s*\n")
PUB_RES = {
    ".rs": re.compile(r"^\s*pub\s"),
    ".ts": re.compile(r"^export\s"),
    ".tsx": re.compile(r"^export\s"),
    ".js": re.compile(r"^export\s"),
    ".jsx": re.compile(r"^export\s"),
    ".dart": re.compile(r"^(class|enum|mixin|extension)\s"),
}


def split_rust_cfg_test(path: Path, text: str) -> tuple[str, str]:
    """Split trailing Rust `#[cfg(test)]` modules out of the production budget."""
    if path.suffix != ".rs":
        return text, ""
    match = CFG_TEST_RE.search(text)
    if not match:
        return text, ""
    return text[: match.start()], text[match.start() :]


def is_test_path(path: Path) -> bool:
    name = path.name
    if name.endswith("_test.dart") or name.endswith("_tests.rs"):
        return True
    if any(name.endswith(s) for s in TEST_SUFFIXES):
        return True
    if name in {"tests.rs", "test.rs"} or name.endswith("_e2e.rs"):
        return True
    parts_lower = [p.lower() for p in path.parts]
    return any(p in {"tests", "test", "__tests__"} for p in parts_lower[:-1])


def is_generated(path: Path, text: str) -> bool:
    if "ontologies" in path.parts and path.suffix == ".ts":
        return True
    return any(marker in text[:800] for marker in GENERATED_MARKERS)


def iter_files(roots: list[Path]) -> list[Path]:
    files: list[Path] = []
    for root in roots:
        if not root.exists():
            raise SystemExit(f"path does not exist: {root}")
        if root.is_file():
            files.append(root)
            continue
        for path in root.rglob("*"):
            if not path.is_file() or path.suffix not in CODE_SUFFIXES:
                continue
            if any(part in SKIP_DIR_NAMES for part in path.parts):
                continue
            if "src/rust" in path.as_posix():
                continue
            files.append(path)
    return sorted(set(files))


def count_file(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="replace")
    generated = is_generated(path, text)
    test = is_test_path(path)
    if generated or test:
        prod_text, inline_test = text, ""
    else:
        prod_text, inline_test = split_rust_cfg_test(path, text)
    prod_lines = prod_text.splitlines()
    inline_test_nonblank = sum(1 for line in inline_test.splitlines() if line.strip())
    nonblank = sum(1 for line in prod_lines if line.strip())
    pub_re = PUB_RES.get(path.suffix)
    public_items = 0
    if not generated and not test and pub_re:
        public_items = sum(1 for line in prod_lines if pub_re.search(line))
    try:
        rel = str(path.resolve().relative_to(REPO))
    except ValueError:
        rel = path.as_posix()
    return {
        "path": rel,
        "physical": len(prod_lines),
        "nonblank": nonblank,
        "public_items": public_items,
        "generated": generated,
        "test": test,
        "inline_test_nonblank": inline_test_nonblank,
    }


def summarize(file_rows: list[dict]) -> dict:
    prod = [row for row in file_rows if not row["test"] and not row["generated"]]
    tests = [row for row in file_rows if row["test"]]
    generated = [row for row in file_rows if row["generated"] and not row["test"]]
    max_row = max(prod, key=lambda row: row["nonblank"], default=None)
    return {
        "production_files": len(prod),
        "production_nonblank": sum(row["nonblank"] for row in prod),
        "production_physical": sum(row["physical"] for row in prod),
        "public_items": sum(row["public_items"] for row in prod),
        "max_file": max_row["path"] if max_row else None,
        "max_file_nonblank": max_row["nonblank"] if max_row else 0,
        "test_nonblank": sum(row["nonblank"] for row in tests)
        + sum(row.get("inline_test_nonblank", 0) for row in prod),
        "generated_nonblank": sum(row["nonblank"] for row in generated),
        "files": file_rows,
    }


def render(summary: dict) -> str:
    return "\n".join(
        [
            f"production files:     {summary['production_files']}",
            f"production non-blank: {summary['production_nonblank']}",
            f"production physical:  {summary['production_physical']}",
            f"public items:         {summary['public_items']}",
            f"largest file:         {summary['max_file']} ({summary['max_file_nonblank']})",
            f"test non-blank:       {summary['test_nonblank']} (excluded from budget)",
            f"generated non-blank:  {summary['generated_nonblank']} (excluded from budget)",
        ]
    )


def compare(before: dict, after: dict, kind: str = "delete-duplicate") -> list[str]:
    failures = []
    if kind == "bind-twins":
        if after["production_nonblank"] > before["production_nonblank"]:
            failures.append(
                "bind-twins: production non-blank lines grew "
                f"({before['production_nonblank']} → {after['production_nonblank']}); "
                "must not add a third copy"
            )
    elif after["production_nonblank"] >= before["production_nonblank"]:
        failures.append(
            "production non-blank lines did not decrease "
            f"({before['production_nonblank']} → {after['production_nonblank']})"
        )
    if after["max_file_nonblank"] > before["max_file_nonblank"]:
        failures.append(
            "largest file in scope grew "
            f"({before['max_file']} {before['max_file_nonblank']} → "
            f"{after['max_file']} {after['max_file_nonblank']})"
        )
    if after["public_items"] > before["public_items"]:
        failures.append(
            "public items in scope grew "
            f"({before['public_items']} → {after['public_items']})"
        )
    return failures


def self_test() -> None:
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "prod.rs").write_text(
            "pub fn a() {}\n\n"
            "pub fn b() {}\n\n"
            "#[cfg(test)]\n"
            "mod tests {\n"
            "    #[test]\n"
            "    fn t() {}\n"
            "}\n"
        )
        (root / "a.test.ts").write_text("export const t = 1;\n")
        (root / "ontologies").mkdir()
        (root / "ontologies" / "core.ts").write_text(
            "/* GENERATED WITH @tomic/cli */\nexport const core = {};\n"
        )
        rows = [count_file(p) for p in iter_files([root])]
        summary = summarize(rows)
        assert summary["production_files"] == 1, summary
        assert summary["production_nonblank"] == 2, summary
        assert summary["public_items"] == 2, summary
        assert summary["test_nonblank"] == 6, summary
        assert summary["generated_nonblank"] == 2, summary

        before = {
            k: summary[k]
            for k in (
                "production_nonblank",
                "max_file",
                "max_file_nonblank",
                "public_items",
            )
        }
        (root / "prod.rs").write_text("pub fn a() {}\n")
        after = summarize([count_file(p) for p in iter_files([root])])
        assert compare(before, after) == [], compare(before, after)

        grown = dict(before)
        grown["production_nonblank"] = before["production_nonblank"] + 1
        assert compare(before, grown), "should fail when lines grow"

        assert compare(before, before, kind="bind-twins") == [], "flat ok for bind-twins"
        assert compare(before, grown, kind="bind-twins"), "bind-twins must not grow"
    print("self-test ok")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--write", type=Path, help="write JSON snapshot")
    parser.add_argument("--baseline", type=Path, help="compare against a prior --write")
    parser.add_argument(
        "--kind",
        choices=("delete-duplicate", "policy-split", "bind-twins", "extract"),
        default="delete-duplicate",
        help="bind-twins allows a flat line count; other kinds require a decrease",
    )
    parser.add_argument("--json", action="store_true", help="print JSON instead of the table")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv)

    if args.self_test:
        self_test()
        return 0

    if not args.paths:
        parser.error("pass one or more files or directories after --")

    roots = [p if p.is_absolute() else REPO / p for p in args.paths]
    summary = summarize([count_file(p) for p in iter_files(roots)])
    payload = {key: value for key, value in summary.items() if key != "files"}
    payload["files"] = [
        {
            key: row[key]
            for key in ("path", "nonblank", "public_items", "test", "generated")
        }
        for row in summary["files"]
    ]

    if args.write:
        args.write.write_text(json.dumps(payload, indent=2) + "\n")

    if args.json:
        print(json.dumps(payload, indent=2))
    else:
        print(render(summary))
        if len(summary["files"]) <= 30:
            print()
            for row in summary["files"]:
                tag = " test" if row["test"] else " generated" if row["generated"] else ""
                print(f"  {row['nonblank']:5d}  {row['path']}{tag}")

    if args.baseline:
        before = json.loads(args.baseline.read_text())
        failures = compare(before, summary, kind=args.kind)
        if failures:
            print("\nGATE FAILED:", file=sys.stderr)
            for failure in failures:
                print(f"  - {failure}", file=sys.stderr)
            return 1
        if args.kind == "bind-twins":
            print(
                "\ngates passed (bind-twins: production lines did not grow; "
                "max file and public items did not grow)"
            )
        else:
            print(
                "\ngates passed (production lines down; max file and public items did not grow)"
            )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
