// @wc-ignore-file
import { DiagnosticCode, type DiagnosticEvent } from '@tomic/lib';

export const DIAGNOSTIC_DB = 'atomic-local-diagnostics-v1';
export const RETENTION_MS = 10 * 60_000;
export const EVENT_LIMIT = 500;
// getRandomValues also works on plain-HTTP self-hosted origins.
export const newDiagnosticId = () =>
  Array.from(crypto.getRandomValues(new Uint32Array(4)), n =>
    n.toString(16),
  ).join('-');
export interface StoredSession {
  id: string;
  startedAt: number;
  savedAt: number;
  events: DiagnosticEvent[];
  totalEvents: number;
  droppedCapacity: number;
  droppedAge: number;
  droppedOperations: number;
  unfinishedOperations: number;
  build: string;
}
export interface DiagnosticState {
  epoch: string;
  enabled: boolean;
  sessions: StoredSession[];
}
export interface DiagnosticStorage {
  update(
    change: (state: DiagnosticState) => DiagnosticState,
  ): Promise<DiagnosticState>;
}
const numeric = (value: unknown): number =>
  typeof value === 'number' && Number.isSafeInteger(value) && value >= 0
    ? value
    : 0;

/** Reconstruct the allowlist even on reads: never export arbitrary stored fields. */
export function cleanState(input: unknown, now = Date.now()): DiagnosticState {
  const raw = (input ?? {}) as Partial<DiagnosticState>;
  const sessions: StoredSession[] = [];

  for (const item of Array.isArray(raw.sessions)
    ? raw.sessions.slice(-20)
    : []) {
    if (
      !item ||
      typeof item.id !== 'string' ||
      !Number.isFinite(item.startedAt) ||
      item.startedAt > now ||
      item.savedAt < now - RETENTION_MS
    )
      continue;
    const events: DiagnosticEvent[] = [];
    let aged = 0;

    for (const event of Array.isArray(item.events)
      ? item.events.slice(-EVENT_LIMIT)
      : []) {
      if (!event || !Object.values(DiagnosticCode).includes(event.code))
        continue;
      const elapsedMs = numeric(event.elapsedMs);

      if (
        item.startedAt + elapsedMs <= now - RETENTION_MS ||
        item.startedAt + elapsedMs > now
      ) {
        aged++;
        continue;
      }

      events.push({
        sequence: numeric(event.sequence),
        elapsedMs,
        code: event.code,
        ...Object.fromEntries(
          ['resource', 'operation', 'pending', 'blocked', 'attempt']
            .filter(
              key => typeof event[key as keyof DiagnosticEvent] === 'number',
            )
            .map(key => [key, numeric(event[key as keyof DiagnosticEvent])]),
        ),
      });
    }

    if (!events.length) continue;
    sessions.push({
      id: item.id.slice(0, 100),
      startedAt: item.startedAt,
      savedAt: Math.min(now, numeric(item.savedAt)),
      events,
      totalEvents: numeric(item.totalEvents),
      droppedAge: numeric(item.droppedAge) + aged,
      droppedCapacity: numeric(item.droppedCapacity),
      droppedOperations: numeric(item.droppedOperations),
      unfinishedOperations: numeric(item.unfinishedOperations),
      // Build identifiers are generated by us, not free-form strings.
      build:
        typeof item.build === 'string' &&
        /^[a-zA-Z0-9.+_-]{1,100}$/.test(item.build)
          ? item.build
          : 'unknown',
    });
  }

  const ordered = sessions
    .flatMap(session => session.events.map(event => ({ session, event })))
    .sort(
      (a, b) =>
        a.session.startedAt +
        a.event.elapsedMs -
        b.session.startedAt -
        b.event.elapsedMs,
    );

  for (const { session } of ordered.slice(
    0,
    Math.max(0, ordered.length - EVENT_LIMIT),
  )) {
    session.events.shift();
    session.droppedCapacity++;
  }

  return {
    epoch: typeof raw.epoch === 'string' ? raw.epoch : newDiagnosticId(),
    enabled: raw.enabled !== false,
    sessions:
      raw.enabled === false
        ? []
        : sessions.filter(session => session.events.length > 0),
  };
}

/** One read/write transaction merges tabs and enforces the origin-wide limit. */
export class IndexedDiagnosticStorage implements DiagnosticStorage {
  private database?: Promise<IDBDatabase>;
  private open(): Promise<IDBDatabase> {
    this.database ??= new Promise((resolve, reject) => {
      const request = indexedDB.open(DIAGNOSTIC_DB, 1);
      let expired = false;
      const timeout = setTimeout(() => {
        expired = true;
        reject(new Error('diagnostic storage unavailable'));
      }, 3000);
      request.onupgradeneeded = () => request.result.createObjectStore('state');

      request.onerror = () => {
        clearTimeout(timeout);
        reject(new Error('diagnostic storage unavailable'));
      };

      request.onsuccess = () => {
        clearTimeout(timeout);
        const db = request.result;

        if (expired) {
          db.close();

          return;
        }

        db.onversionchange = () => db.close();
        resolve(db);
      };
    });

    return this.database.catch(error => {
      this.database = undefined;
      throw error;
    });
  }
  async update(
    change: (state: DiagnosticState) => DiagnosticState,
  ): Promise<DiagnosticState> {
    const db = await this.open();

    return new Promise((resolve, reject) => {
      const tx = db.transaction('state', 'readwrite');
      const timeout = setTimeout(() => tx.abort(), 3000);
      let result: DiagnosticState;

      tx.oncomplete = () => {
        clearTimeout(timeout);
        resolve(result);
      };

      tx.onabort = tx.onerror = () => {
        clearTimeout(timeout);
        reject(new Error('diagnostic storage unavailable'));
      };

      const records = tx.objectStore('state');
      const request = records.get('rolling');

      request.onsuccess = () => {
        try {
          result = cleanState(change(cleanState(request.result)));
          records.put(result, 'rolling');
        } catch {
          tx.abort();
        }
      };
    });
  }
}
