// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CanvasListItemJson`, `DbEventDto`

class AgentInfo {
  final String secret;
  final String subject;
  final String publicKey;
  final String? name;

  const AgentInfo({
    required this.secret,
    required this.subject,
    required this.publicKey,
    this.name,
  });

  @override
  int get hashCode =>
      secret.hashCode ^ subject.hashCode ^ publicKey.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentInfo &&
          runtimeType == other.runtimeType &&
          secret == other.secret &&
          subject == other.subject &&
          publicKey == other.publicKey &&
          name == other.name;
}

class CanvasListItem {
  final String subject;
  final String name;

  /// Unix milliseconds (`dateEdited` property).
  final PlatformInt64 dateEdited;

  const CanvasListItem({
    required this.subject,
    required this.name,
    required this.dateEdited,
  });

  @override
  int get hashCode => subject.hashCode ^ name.hashCode ^ dateEdited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CanvasListItem &&
          runtimeType == other.runtimeType &&
          subject == other.subject &&
          name == other.name &&
          dateEdited == other.dateEdited;
}

class FolderListItem {
  final String subject;
  final String name;

  const FolderListItem({
    required this.subject,
    required this.name,
  });

  @override
  int get hashCode => subject.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderListItem &&
          runtimeType == other.runtimeType &&
          subject == other.subject &&
          name == other.name;
}

class SetupResult {
  final String agentSecret;
  final String agentSubject;
  final String driveSubject;

  const SetupResult({
    required this.agentSecret,
    required this.agentSubject,
    required this.driveSubject,
  });

  @override
  int get hashCode =>
      agentSecret.hashCode ^ agentSubject.hashCode ^ driveSubject.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetupResult &&
          runtimeType == other.runtimeType &&
          agentSecret == other.agentSecret &&
          agentSubject == other.agentSubject &&
          driveSubject == other.driveSubject;
}

/// Metadata for a single historical version of a resource.
class VersionMetadata {
  final Uint8List id;
  final PlatformInt64 timestamp;
  final String peerId;
  final BigInt lamport;
  final int len;
  final String? message;

  const VersionMetadata({
    required this.id,
    required this.timestamp,
    required this.peerId,
    required this.lamport,
    required this.len,
    this.message,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      timestamp.hashCode ^
      peerId.hashCode ^
      lamport.hashCode ^
      len.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VersionMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          timestamp == other.timestamp &&
          peerId == other.peerId &&
          lamport == other.lamport &&
          len == other.len &&
          message == other.message;
}
