/**
 * Session certificates — TypeScript mirror of `lib/src/session_cert.rs`.
 *
 * A **root** Agent is the person: its DID is what `write` lists name and what
 * `createdBy` records. A **session** Agent is this browser — a fresh Ed25519
 * keypair generated here, whose private half never leaves, and which the root
 * signs a short-lived certificate over. The session key signs commits and
 * authentication proofs; every rights check on the node is answered for the
 * root.
 *
 * The two implementations MUST produce byte-identical `encodeSessionCert`
 * output, or a commit signed in this browser will not verify on the node. The
 * fixed binary layout (deliberately NOT JSON, so there is no canonicalization
 * ambiguity in the trust path) is what makes that reliable, and the shared
 * golden fixture is what proves it.
 *
 * See `planning/oidc-oauth.md`.
 */
import { sha512 } from '@noble/hashes/sha2.js';
import { getPublicKey, hashes, sign, verify } from '@noble/ed25519';
import { decodeB64, encodeB64Url } from './base64.js';

// Match `CryptoProvider.ts`: the synchronous noble API needs sha512 installed.
hashes.sha512 = sha512;

/**
 * Certificate format version, and the first signed byte.
 *
 * Deliberately not `0x01`, which is `GENESIS_VERSION_V1`. Both certificates are
 * Ed25519 signatures by an agent key over a compact binary blob, so if their
 * signed payloads could be read as each other, a genesis certificate of the
 * right length would double as a session certificate. Distinct leading bytes
 * make the two payload languages disjoint at the first byte.
 */
export const SESSION_CERT_VERSION_V1 = 0x53;

/**
 * The commit propval a certificate rides on. Declared here rather than in
 * `ontologies/commits.ts`, which is generated by `@tomic/cli` and would lose a
 * hand-written entry on the next regeneration. Mirrors
 * `atomic_lib::urls::SESSION_CERT`.
 */
export const SESSION_CERT_PROPERTY =
  'https://atomicdata.dev/properties/sessionCert';

/** The same certificate on an Authentication resource. Mirrors the serde
 *  rename on `atomic_lib::authentication::AuthValues`. */
export const AUTH_SESSION_CERT_PROPERTY =
  'https://atomicdata.dev/properties/auth/sessionCert';

/** Bytes covered by the signature: everything before it. */
const SIGNED_LEN = 81;

/** Total encoded length: {@link SIGNED_LEN} plus the 64-byte signature. */
export const SESSION_CERT_LEN = SIGNED_LEN + 64;

/** The unsigned half — what a root Agent commits to when it signs. */
export interface SessionCertClaims {
  /** The delegated key (raw 32 bytes). Whatever signs a commit or an auth
   *  proof carrying this certificate must be exactly this key. */
  sessionPubkey: Uint8Array;
  /** Start of the validity window, Unix milliseconds. */
  notBefore: number;
  /** End of the validity window, Unix milliseconds. */
  notAfter: number;
  /** The issuing root Agent's key (raw 32 bytes). Rights are answered for
   *  this identity. */
  rootPubkey: Uint8Array;
}

/** A root Agent's signed statement that a session key may act for it. */
export interface SessionCert extends SessionCertClaims {
  /** Ed25519 signature by `rootPubkey` over bytes [0, 81). */
  signature: Uint8Array;
}

function assertKey(bytes: Uint8Array, name: string): void {
  if (bytes.length !== 32) {
    throw new Error(`Session certificate ${name} must be 32 bytes`);
  }
}

/**
 * The exact bytes a root signs. Shared by signing and verification so the two
 * can never drift.
 *
 * ```text
 * offset  size  field
 * 0       1     version        0x53
 * 1       32    sessionPubKey  Ed25519 raw
 * 33      8     notBefore      i64 unix ms, little-endian
 * 41      8     notAfter       i64 unix ms, little-endian
 * 49      32    rootPubKey     Ed25519 raw
 * ```
 */
export function encodeSessionCertClaims(claims: SessionCertClaims): Uint8Array {
  assertKey(claims.sessionPubkey, 'session public key');
  assertKey(claims.rootPubkey, 'root public key');

  const out = new Uint8Array(SIGNED_LEN);
  out[0] = SESSION_CERT_VERSION_V1;
  out.set(claims.sessionPubkey, 1);
  out.set(claims.rootPubkey, 49);

  // Signed 64-bit, little-endian: `notAfter` may legitimately be negative in a
  // test vector, and a `setUint32` pair would encode that wrongly.
  const view = new DataView(out.buffer, out.byteOffset, out.byteLength);
  view.setBigInt64(33, BigInt(claims.notBefore), true);
  view.setBigInt64(41, BigInt(claims.notAfter), true);

  return out;
}

/** Serialize the full certificate: the signed claims followed by the
 *  signature. */
export function encodeSessionCert(cert: SessionCert): Uint8Array {
  if (cert.signature.length !== 64) {
    throw new Error('Session certificate signature must be 64 bytes');
  }

  const out = new Uint8Array(SESSION_CERT_LEN);
  out.set(encodeSessionCertClaims(cert), 0);
  out.set(cert.signature, SIGNED_LEN);

  return out;
}

/** Base64url form, which is how the certificate travels on a commit propval
 *  and in an authentication header. */
export function encodeSessionCertB64(cert: SessionCert): string {
  return encodeB64Url(encodeSessionCert(cert));
}

/** Parse the canonical binary layout. Rejects unknown versions, truncated
 *  input, and trailing bytes. */
export function decodeSessionCert(bytes: Uint8Array): SessionCert {
  if (bytes.length < SESSION_CERT_LEN) {
    throw new Error('Session certificate is truncated');
  }

  if (bytes.length > SESSION_CERT_LEN) {
    throw new Error('Session certificate has trailing bytes');
  }

  if (bytes[0] !== SESSION_CERT_VERSION_V1) {
    throw new Error(`Unsupported session certificate version ${bytes[0]}`);
  }

  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

  return {
    sessionPubkey: bytes.slice(1, 33),
    notBefore: Number(view.getBigInt64(33, true)),
    notAfter: Number(view.getBigInt64(41, true)),
    rootPubkey: bytes.slice(49, 81),
    signature: bytes.slice(81, SESSION_CERT_LEN),
  };
}

/** Parse the base64url form. */
export function decodeSessionCertB64(value: string): SessionCert {
  return decodeSessionCert(decodeB64(value));
}

/** The issuing root Agent's DID — the identity every rights check is answered
 *  for. */
export function sessionCertRootDid(cert: SessionCertClaims): string {
  return `did:ad:agent:${encodeB64Url(cert.rootPubkey)}`;
}

/** The delegated session Agent's DID. Never put this in an ACL: it outlives
 *  its certificate there. */
export function sessionCertSessionDid(cert: SessionCertClaims): string {
  return `did:ad:agent:${encodeB64Url(cert.sessionPubkey)}`;
}

/**
 * Sign a certificate with the root's raw 32-byte Ed25519 private key.
 *
 * In the shipped OIDC flow this runs on the node, which is where the root key
 * lives; it is here so a test, a local tool, or a future browser-held root can
 * mint one without a second implementation of the layout.
 */
export async function signSessionCert(
  claims: SessionCertClaims,
  rootPrivateKey: Uint8Array,
): Promise<SessionCert> {
  const derived = await getPublicKey(rootPrivateKey);

  if (encodeB64Url(derived) !== encodeB64Url(claims.rootPubkey)) {
    throw new Error(
      'Session certificate root pubkey does not match the signing key',
    );
  }

  return {
    ...claims,
    signature: await sign(encodeSessionCertClaims(claims), rootPrivateKey),
  };
}

/**
 * Verify the certificate and return the root Agent's DID.
 *
 * 1. `claimedSessionPubkey` is the key that actually signed the commit or auth
 *    proof; it must be the key this certificate delegates to.
 * 2. The root's Ed25519 signature must cover the claims.
 * 3. `t` must fall inside `[notBefore, notAfter]`. On a commit that is
 *    `createdAt`, so history stays valid after the window closes; on a live
 *    request it is the auth timestamp.
 *
 * Throws on any failure — there is no "probably fine" answer to who signed.
 */
export async function verifySessionCert(
  cert: SessionCert,
  claimedSessionPubkey: Uint8Array,
  t: number,
): Promise<string> {
  if (encodeB64Url(cert.sessionPubkey) !== encodeB64Url(claimedSessionPubkey)) {
    throw new Error(
      'Session certificate was issued for a different key than the one that signed',
    );
  }

  const ok = await verify(
    cert.signature,
    encodeSessionCertClaims(cert),
    cert.rootPubkey,
  );

  if (!ok) {
    throw new Error('Session certificate signature is invalid');
  }

  if (t < cert.notBefore) {
    throw new Error(
      `Session certificate is not valid yet: ${t} is before ${cert.notBefore}`,
    );
  }

  if (t > cert.notAfter) {
    throw new Error(
      `Session certificate expired: ${t} is after ${cert.notAfter}`,
    );
  }

  return sessionCertRootDid(cert);
}

/**
 * Half the window has gone by — the point at which a client refreshes.
 *
 * Refreshing early is what keeps a daily user from ever seeing a redirect, and
 * what makes an expired certificate cost one extra round trip at drain time
 * rather than a lost edit.
 */
export function sessionCertNeedsRefresh(
  cert: SessionCertClaims,
  now: number = Date.now(),
): boolean {
  const halfway = cert.notBefore + (cert.notAfter - cert.notBefore) / 2;

  return now >= halfway;
}
