// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_drive_materialized`, `fetch_resource_state`, `handle_ws_message`, `ws_client_slot`, `ws_task_slot`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `try_push_commit`

/// `http://host:9883` → `ws://host:9883/ws`
Future<String> serverOriginToWsUrl({required String origin}) =>
    RustLib.instance.api
        .crateApiSimpleWsSyncServerOriginToWsUrl(origin: origin);

Future<void> closeWsSync() =>
    RustLib.instance.api.crateApiSimpleWsSyncCloseWsSync();

Future<void> openWsSync({required String serverOrigin}) => RustLib.instance.api
    .crateApiSimpleWsSyncOpenWsSync(serverOrigin: serverOrigin);

/// Subscribe to live updates for a single resource over WebSocket.
Future<void> subscribeResource({required String subject}) =>
    RustLib.instance.api
        .crateApiSimpleWsSyncSubscribeResource(subject: subject);

/// Post a commit JSON-AD over the open WS session (falls back to error if closed).
Future<String> postCommitOverWs({required String commitJson}) =>
    RustLib.instance.api
        .crateApiSimpleWsSyncPostCommitOverWs(commitJson: commitJson);
